/*! Video.js v4.5.2 Copyright 2014 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */ 
(function() {var b=void 0,f=!0,j=null,l=!1;function m(){return function(){}}function q(a){return function(){return this[a]}}function r(a){return function(){return a}}var t;document.createElement("video");document.createElement("audio");document.createElement("track");function u(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.wa[a])return u.wa[a];a=u.v(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new u.Player(a,c,d)}
var videojs=u;window.Zd=window.$d=u;u.Sb="4.5";u.Gc="https:"==document.location.protocol?"https://":"http://";u.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}},notSupportedMessage:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'};
"GENERATED_CDN_VSN"!==u.Sb&&(videojs.options.flash.swf=u.Gc+"vjs.zencdn.net/"+u.Sb+"/video-js.swf");u.wa={};"function"===typeof define&&define.amd?define([],function(){return videojs}):"object"===typeof exports&&"object"===typeof module&&(module.exports=videojs);u.la=u.CoreObject=m();
u.la.extend=function(a){var c,d;a=a||{};c=a.init||a.i||this.prototype.init||this.prototype.i||m();d=function(){c.apply(this,arguments)};d.prototype=u.l.create(this.prototype);d.prototype.constructor=d;d.extend=u.la.extend;d.create=u.la.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};u.la.create=function(){var a=u.l.create(this.prototype);this.apply(a,arguments);return a};
u.d=function(a,c,d){var e=u.getData(a);e.z||(e.z={});e.z[c]||(e.z[c]=[]);d.t||(d.t=u.t++);e.z[c].push(d);e.W||(e.disabled=l,e.W=function(c){if(!e.disabled){c=u.kc(c);var d=e.z[c.type];if(d)for(var d=d.slice(0),k=0,p=d.length;k<p&&!c.rc();k++)d[k].call(a,c)}});1==e.z[c].length&&(document.addEventListener?a.addEventListener(c,e.W,l):document.attachEvent&&a.attachEvent("on"+c,e.W))};
u.o=function(a,c,d){if(u.oc(a)){var e=u.getData(a);if(e.z)if(c){var g=e.z[c];if(g){if(d){if(d.t)for(e=0;e<g.length;e++)g[e].t===d.t&&g.splice(e--,1)}else e.z[c]=[];u.gc(a,c)}}else for(g in e.z)c=g,e.z[c]=[],u.gc(a,c)}};u.gc=function(a,c){var d=u.getData(a);0===d.z[c].length&&(delete d.z[c],document.removeEventListener?a.removeEventListener(c,d.W,l):document.detachEvent&&a.detachEvent("on"+c,d.W));u.zb(d.z)&&(delete d.z,delete d.W,delete d.disabled);u.zb(d)&&u.wc(a)};
u.kc=function(a){function c(){return f}function d(){return l}if(!a||!a.Ab){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&("layerY"!==g&&"keyboardEvent.keyLocation"!==g)&&("returnValue"==g&&e.preventDefault||(a[g]=e[g]));a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=l;a.gd=c;a.defaultPrevented=f};a.gd=d;a.defaultPrevented=l;a.stopPropagation=function(){e.stopPropagation&&
e.stopPropagation();a.cancelBubble=f;a.Ab=c};a.Ab=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&e.stopImmediatePropagation();a.rc=c;a.stopPropagation()};a.rc=d;if(a.clientX!=j){g=document.documentElement;var h=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=j&&(a.button=a.button&1?0:a.button&
4?1:a.button&2?2:0)}return a};u.k=function(a,c){var d=u.oc(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=u.kc(c);d.W&&d.W.call(a,c);if(e&&!c.Ab()&&c.bubbles!==l)u.k(e,c);else if(!e&&!c.defaultPrevented&&(d=u.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=l}return!c.defaultPrevented};
u.U=function(a,c,d){function e(){u.o(a,c,e);d.apply(this,arguments)}e.t=d.t=d.t||u.t++;u.d(a,c,e)};var v=Object.prototype.hasOwnProperty;u.e=function(a,c){var d,e;d=document.createElement(a||"div");for(e in c)v.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};u.Z=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.l={};u.l.create=Object.create||function(a){function c(){}c.prototype=a;return new c};
u.l.sa=function(a,c,d){for(var e in a)v.call(a,e)&&c.call(d||this,e,a[e])};u.l.A=function(a,c){if(!c)return a;for(var d in c)v.call(c,d)&&(a[d]=c[d]);return a};u.l.Xc=function(a,c){var d,e,g;a=u.l.copy(a);for(d in c)v.call(c,d)&&(e=a[d],g=c[d],a[d]=u.l.Oa(e)&&u.l.Oa(g)?u.l.Xc(e,g):c[d]);return a};u.l.copy=function(a){return u.l.A({},a)};u.l.Oa=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};
u.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.t||(c.t=u.t++);e.t=d?d+"_"+c.t:c.t;return e};u.qa={};u.t=1;u.expando="vdata"+(new Date).getTime();u.getData=function(a){var c=a[u.expando];c||(c=a[u.expando]=u.t++,u.qa[c]={});return u.qa[c]};u.oc=function(a){a=a[u.expando];return!(!a||u.zb(u.qa[a]))};u.wc=function(a){var c=a[u.expando];if(c){delete u.qa[c];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=j}}};
u.zb=function(a){for(var c in a)if(a[c]!==j)return l;return f};u.m=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};u.r=function(a,c){var d,e;if(-1!=a.className.indexOf(c)){d=a.className.split(" ");for(e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};u.G=u.e("video");u.J=navigator.userAgent;u.Lc=/iPhone/i.test(u.J);u.Kc=/iPad/i.test(u.J);u.Mc=/iPod/i.test(u.J);u.Jc=u.Lc||u.Kc||u.Mc;var aa=u,w;var x=u.J.match(/OS (\d+)_/i);
w=x&&x[1]?x[1]:b;aa.Nd=w;u.Ic=/Android/i.test(u.J);var ba=u,y;var z=u.J.match(/Android (\d+)(?:\.(\d+))?(?:\.(\d+))*/i),A,B;z?(A=z[1]&&parseFloat(z[1]),B=z[2]&&parseFloat(z[2]),y=A&&B?parseFloat(z[1]+"."+z[2]):A?A:j):y=j;ba.Rb=y;u.Nc=u.Ic&&/webkit/i.test(u.J)&&2.3>u.Rb;u.Vb=/Firefox/i.test(u.J);u.Od=/Chrome/i.test(u.J);u.bc=!!("ontouchstart"in window||window.Hc&&document instanceof window.Hc);
u.wb=function(a){var c,d,e,g;c={};if(a&&a.attributes&&0<a.attributes.length){d=a.attributes;for(var h=d.length-1;0<=h;h--){e=d[h].name;g=d[h].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==j?f:l;c[e]=g}}return c};
u.Sd=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};u.yb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};u.Ob={};u.v=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.ua=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),h=Math.floor(c/60%60),k=Math.floor(c/3600);if(isNaN(a)||Infinity===a)g=e=d="-";g=0<g||0<k?g+":":"";return g+(((g||10<=h)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.Tc=function(){document.body.focus();document.onselectstart=r(l)};u.Hd=function(){document.onselectstart=r(f)};u.trim=function(a){return(a+"").replace(/^\s+|\s+$/g,"")};u.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};
u.tb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
u.get=function(a,c,d,e){var g,h,k,p;d=d||m();"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});h=new XMLHttpRequest;k=u.ud(a);p=window.location;k.protocol+k.host!==p.protocol+p.host&&window.XDomainRequest&&!("withCredentials"in
h)?(h=new window.XDomainRequest,h.onload=function(){c(h.responseText)},h.onerror=d,h.onprogress=m(),h.ontimeout=d):(g="file:"==k.protocol||"file:"==p.protocol,h.onreadystatechange=function(){4===h.readyState&&(200===h.status||g&&0===h.status?c(h.responseText):d(h.responseText))});try{h.open("GET",a,f),e&&(h.withCredentials=f)}catch(n){d(n);return}try{h.send()}catch(s){d(s)}};
u.zd=function(a){try{var c=window.localStorage||l;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):18==d.code?u.log("LocalStorage not allowed (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.mc=function(a){a.match(/^https?:\/\//)||(a=u.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.ud=function(a){var c,d,e,g;g="protocol hostname port pathname search hash host".split(" ");d=u.e("a",{href:a});if(e=""===d.host&&"file:"!==d.protocol)c=u.e("div"),c.innerHTML='<a href="'+a+'"></a>',d=c.firstChild,c.setAttribute("style","display:none; position:absolute;"),document.body.appendChild(c);a={};for(var h=0;h<g.length;h++)a[g[h]]=d[g[h]];e&&document.body.removeChild(c);return a};u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};
u.dd=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:u.round(c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0)),top:u.round(c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0))}};u.ka={};u.ka.Eb=function(a,c){var d,e,g;a=u.l.copy(a);for(d in c)c.hasOwnProperty(d)&&(e=a[d],g=c[d],a[d]=u.l.Oa(e)&&u.l.Oa(g)?u.ka.Eb(e,g):c[d]);return a};
u.b=u.la.extend({i:function(a,c,d){this.c=a;this.j=u.l.copy(this.j);c=this.options(c);this.R=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+u.t++);this.md=c.name||j;this.a=c.el||this.e();this.K=[];this.Ka={};this.La={};this.pc();this.I(d);if(c.xc!==l){var e,g;e=u.bind(this.B(),this.B().reportUserActivity);this.d("touchstart",function(){e();clearInterval(g);g=setInterval(e,250)});a=function(){e();clearInterval(g)};this.d("touchmove",e);this.d("touchend",a);this.d("touchcancel",a)}}});t=u.b.prototype;
t.dispose=function(){this.k({type:"dispose",bubbles:l});if(this.K)for(var a=this.K.length-1;0<=a;a--)this.K[a].dispose&&this.K[a].dispose();this.La=this.Ka=this.K=j;this.o();this.a.parentNode&&this.a.parentNode.removeChild(this.a);u.wc(this.a);this.a=j};t.c=f;t.B=q("c");t.options=function(a){return a===b?this.j:this.j=u.ka.Eb(this.j,a)};t.e=function(a,c){return u.e(a,c)};t.v=q("a");t.fa=function(){return this.C||this.a};t.id=q("R");t.name=q("md");t.children=q("K");t.fd=function(a){return this.Ka[a]};
t.ga=function(a){return this.La[a]};t.V=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||u.Z(e),c.name=e,d=new window.videojs[d](this.c||this,c)):d=a;this.K.push(d);"function"===typeof d.id&&(this.Ka[d.id()]=d);(e=e||d.name&&d.name())&&(this.La[e]=d);"function"===typeof d.el&&d.el()&&this.fa().appendChild(d.el());return d};
t.removeChild=function(a){"string"===typeof a&&(a=this.ga(a));if(a&&this.K){for(var c=l,d=this.K.length-1;0<=d;d--)if(this.K[d]===a){c=f;this.K.splice(d,1);break}c&&(this.Ka[a.id]=j,this.La[a.name]=j,(c=a.v())&&c.parentNode===this.fa()&&this.fa().removeChild(a.v()))}};t.pc=function(){var a,c,d,e;a=this;if(c=this.options().children)if(c instanceof Array)for(var g=0;g<c.length;g++)d=c[g],"string"==typeof d?(e=d,d={}):e=d.name,a[e]=a.V(e,d);else u.l.sa(c,function(c,d){d!==l&&(a[c]=a.V(c,d))})};t.Q=r("");
t.d=function(a,c){u.d(this.a,a,u.bind(this,c));return this};t.o=function(a,c){u.o(this.a,a,c);return this};t.U=function(a,c){u.U(this.a,a,u.bind(this,c));return this};t.k=function(a,c){u.k(this.a,a,c);return this};t.I=function(a){a&&(this.aa?a.call(this):(this.Va===b&&(this.Va=[]),this.Va.push(a)));return this};t.Aa=function(){this.aa=f;var a=this.Va;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.Va=[];this.k("ready")}};t.m=function(a){u.m(this.a,a);return this};
t.r=function(a){u.r(this.a,a);return this};t.show=function(){this.a.style.display="block";return this};t.D=function(){this.a.style.display="none";return this};function C(a){a.r("vjs-lock-showing")}t.disable=function(){this.D();this.show=m()};t.width=function(a,c){return E(this,"width",a,c)};t.height=function(a,c){return E(this,"height",a,c)};t.Zc=function(a,c){return this.width(a,f).height(c)};
function E(a,c,d,e){if(d!==b)return a.a.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.k("resize"),a;if(!a.a)return 0;d=a.a.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+u.Z(c)],10)}
function F(a){var c,d,e,g,h,k,p,n;c=0;d=j;a.d("touchstart",function(a){1===a.touches.length&&(d=a.touches[0],c=(new Date).getTime(),g=f)});a.d("touchmove",function(a){1<a.touches.length?g=l:d&&(k=a.touches[0].pageX-d.pageX,p=a.touches[0].pageY-d.pageY,n=Math.sqrt(k*k+p*p),22<n&&(g=l))});h=function(){g=l};a.d("touchleave",h);a.d("touchcancel",h);a.d("touchend",function(a){d=j;g===f&&(e=(new Date).getTime()-c,250>e&&(a.preventDefault(),this.k("tap")))})}
u.q=u.b.extend({i:function(a,c){u.b.call(this,a,c);F(this);this.d("tap",this.p);this.d("click",this.p);this.d("focus",this.Ra);this.d("blur",this.Qa)}});t=u.q.prototype;t.e=function(a,c){c=u.l.A({className:this.Q(),innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">'+(this.pa||"Need Text")+"</span></div>",role:"button","aria-live":"polite",tabIndex:0},c);return u.b.prototype.e.call(this,a,c)};t.Q=function(){return"vjs-control "+u.b.prototype.Q.call(this)};t.p=m();
t.Ra=function(){u.d(document,"keyup",u.bind(this,this.ba))};t.ba=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.p()};t.Qa=function(){u.o(document,"keyup",u.bind(this,this.ba))};
u.O=u.b.extend({i:function(a,c){u.b.call(this,a,c);this.Sc=this.ga(this.j.barName);this.handle=this.ga(this.j.handleName);this.d("mousedown",this.Sa);this.d("touchstart",this.Sa);this.d("focus",this.Ra);this.d("blur",this.Qa);this.d("click",this.p);this.c.d("controlsvisible",u.bind(this,this.update));a.d(this.uc,u.bind(this,this.update));this.P={}}});t=u.O.prototype;
t.e=function(a,c){c=c||{};c.className+=" vjs-slider";c=u.l.A({role:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return u.b.prototype.e.call(this,a,c)};t.Sa=function(a){a.preventDefault();u.Tc();this.P.move=u.bind(this,this.Gb);this.P.end=u.bind(this,this.Hb);u.d(document,"mousemove",this.P.move);u.d(document,"mouseup",this.P.end);u.d(document,"touchmove",this.P.move);u.d(document,"touchend",this.P.end);this.Gb(a)};
t.Hb=function(){u.Hd();u.o(document,"mousemove",this.P.move,l);u.o(document,"mouseup",this.P.end,l);u.o(document,"touchmove",this.P.move,l);u.o(document,"touchend",this.P.end,l);this.update()};t.update=function(){if(this.a){var a,c=this.xb(),d=this.handle,e=this.Sc;isNaN(c)&&(c=0);a=c;if(d){a=this.a.offsetWidth;var g=d.v().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.v().style.left=u.round(100*c,2)+"%"}e.v().style.width=u.round(100*a,2)+"%"}};
function G(a,c){var d,e,g,h;d=a.a;e=u.dd(d);h=g=d.offsetWidth;d=a.handle;if(a.j.Jd)return h=e.top,e=c.changedTouches?c.changedTouches[0].pageY:c.pageY,d&&(d=d.v().offsetHeight,h+=d/2,g-=d),Math.max(0,Math.min(1,(h-e+g)/g));g=e.left;e=c.changedTouches?c.changedTouches[0].pageX:c.pageX;d&&(d=d.v().offsetWidth,g+=d/2,h-=d);return Math.max(0,Math.min(1,(e-g)/h))}t.Ra=function(){u.d(document,"keyup",u.bind(this,this.ba))};
t.ba=function(a){37==a.which?(a.preventDefault(),this.zc()):39==a.which&&(a.preventDefault(),this.Ac())};t.Qa=function(){u.o(document,"keyup",u.bind(this,this.ba))};t.p=function(a){a.stopImmediatePropagation();a.preventDefault()};u.X=u.b.extend();u.X.prototype.defaultValue=0;u.X.prototype.e=function(a,c){c=c||{};c.className+=" vjs-slider-handle";c=u.l.A({innerHTML:'<span class="vjs-control-text">'+this.defaultValue+"</span>"},c);return u.b.prototype.e.call(this,"div",c)};u.ma=u.b.extend();
function ca(a,c){a.V(c);c.d("click",u.bind(a,function(){C(this)}))}u.ma.prototype.e=function(){var a=this.options().Vc||"ul";this.C=u.e(a,{className:"vjs-menu-content"});a=u.b.prototype.e.call(this,"div",{append:this.C,className:"vjs-menu"});a.appendChild(this.C);u.d(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};u.N=u.q.extend({i:function(a,c){u.q.call(this,a,c);this.selected(c.selected)}});
u.N.prototype.e=function(a,c){return u.q.prototype.e.call(this,"li",u.l.A({className:"vjs-menu-item",innerHTML:this.j.label},c))};u.N.prototype.p=function(){this.selected(f)};u.N.prototype.selected=function(a){a?(this.m("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.r("vjs-selected"),this.a.setAttribute("aria-selected",l))};
u.S=u.q.extend({i:function(a,c){u.q.call(this,a,c);this.va=this.Ma();this.V(this.va);this.L&&0===this.L.length&&this.D();this.d("keyup",this.ba);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}});t=u.S.prototype;t.oa=l;t.Ma=function(){var a=new u.ma(this.c);this.options().title&&a.fa().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.Z(this.options().title),Fd:-1}));if(this.L=this.createItems())for(var c=0;c<this.L.length;c++)ca(a,this.L[c]);return a};
t.ra=m();t.Q=function(){return this.className+" vjs-menu-button "+u.q.prototype.Q.call(this)};t.Ra=m();t.Qa=m();t.p=function(){this.U("mouseout",u.bind(this,function(){C(this.va);this.a.blur()}));this.oa?H(this):I(this)};t.ba=function(a){a.preventDefault();32==a.which||13==a.which?this.oa?H(this):I(this):27==a.which&&this.oa&&H(this)};function I(a){a.oa=f;a.va.m("vjs-lock-showing");a.a.setAttribute("aria-pressed",f);a.L&&0<a.L.length&&a.L[0].v().focus()}
function H(a){a.oa=l;C(a.va);a.a.setAttribute("aria-pressed",l)}
u.Player=u.b.extend({i:function(a,c,d){this.M=a;a.id=a.id||"vjs_video_"+u.t++;c=u.l.A(da(a),c);this.u={};this.vc=c.poster;this.sb=c.controls;a.controls=l;c.xc=l;u.b.call(this,this,c,d);this.controls()?this.m("vjs-controls-enabled"):this.m("vjs-controls-disabled");this.d("loadstart",this.qd);this.d("ended",this.nd);this.d("play",this.Jb);this.d("firstplay",this.od);this.d("pause",this.Ib);this.d("progress",this.rd);this.d("durationchange",this.sc);this.d("error",this.Fb);this.d("fullscreenchange",
this.pd);u.wa[this.R]=this;c.plugins&&u.l.sa(c.plugins,function(a,c){this[a](c)},this);var e,g,h,k,p,n;e=u.bind(this,this.reportUserActivity);this.d("mousedown",function(){e();clearInterval(g);g=setInterval(e,250)});this.d("mousemove",function(a){if(a.screenX!=p||a.screenY!=n)p=a.screenX,n=a.screenY,e()});this.d("mouseup",function(){e();clearInterval(g)});this.d("keydown",e);this.d("keyup",e);h=setInterval(u.bind(this,function(){this.ja&&(this.ja=l,this.userActive(f),clearTimeout(k),k=setTimeout(u.bind(this,
function(){this.ja||this.userActive(l)}),2E3))}),250);this.d("dispose",function(){clearInterval(h);clearTimeout(k)})}});t=u.Player.prototype;t.j=u.options;t.dispose=function(){this.k("dispose");this.o("dispose");u.wa[this.R]=j;this.M&&this.M.player&&(this.M.player=j);this.a&&this.a.player&&(this.a.player=j);clearInterval(this.Ua);this.xa();this.f&&this.f.dispose();u.b.prototype.dispose.call(this)};
function da(a){var c={sources:[],tracks:[]};u.l.A(c,u.wb(a));if(a.hasChildNodes()){var d,e,g,h;a=a.childNodes;g=0;for(h=a.length;g<h;g++)d=a[g],e=d.nodeName.toLowerCase(),"source"===e?c.sources.push(u.wb(d)):"track"===e&&c.tracks.push(u.wb(d))}return c}
t.e=function(){var a=this.a=u.b.prototype.e.call(this,"div"),c=this.M;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes()){var d,e,g,h,k;d=c.childNodes;e=d.length;for(k=[];e--;)g=d[e],h=g.nodeName.toLowerCase(),"track"===h&&k.push(g);for(d=0;d<k.length;d++)c.removeChild(k[d])}a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.m("vjs-paused");this.width(this.j.width,f);this.height(this.j.height,f);c.parentNode&&c.parentNode.insertBefore(a,
c);u.yb(c,a);return a};
function J(a,c,d){a.f&&(a.aa=l,a.f.dispose(),a.Cb&&(a.Cb=l,clearInterval(a.Ua)),a.Db&&K(a),a.f=l);"Html5"!==c&&a.M&&(u.h.ic(a.M),a.M=j);a.ya=c;a.aa=l;var e=u.l.A({source:d,parentEl:a.a},a.j[c.toLowerCase()]);d&&(d.src==a.u.src&&0<a.u.currentTime&&(e.startTime=a.u.currentTime),a.u.src=d.src);a.f=new window.videojs[c](a,e);a.f.I(function(){this.c.Aa();if(!this.n.progressEvents){var a=this.c;a.Cb=f;a.Ua=setInterval(u.bind(a,function(){this.u.nb<this.buffered().end(0)?this.k("progress"):1==this.bufferedPercent()&&
(clearInterval(this.Ua),this.k("progress"))}),500);a.f&&a.f.U("progress",function(){this.n.progressEvents=f;var a=this.c;a.Cb=l;clearInterval(a.Ua)})}this.n.timeupdateEvents||(a=this.c,a.Db=f,a.d("play",a.Dc),a.d("pause",a.xa),a.f&&a.f.U("timeupdate",function(){this.n.timeupdateEvents=f;K(this.c)}))})}function K(a){a.Db=l;a.xa();a.o("play",a.Dc);a.o("pause",a.xa)}t.Dc=function(){this.hc&&this.xa();this.hc=setInterval(u.bind(this,function(){this.k("timeupdate")}),250)};
t.xa=function(){clearInterval(this.hc);this.k("timeupdate")};t.qd=function(){this.o("play",L);this.U("play",L);u.r(this.a,"vjs-has-started")};function L(a){u.k(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())}t.Jb=function(){u.r(this.a,"vjs-paused");u.m(this.a,"vjs-playing")};t.od=function(){this.j.starttime&&this.currentTime(this.j.starttime);this.m("vjs-has-started")};t.Ib=function(){u.r(this.a,"vjs-playing");u.m(this.a,"vjs-paused")};
t.rd=function(){1==this.bufferedPercent()&&this.k("loadedalldata")};t.nd=function(){this.j.loop&&(this.currentTime(0),this.play())};t.sc=function(){var a=M(this,"duration");a&&(0>a&&(a=Infinity),this.duration(a),Infinity===a?this.m("vjs-live"):this.r("vjs-live"))};t.pd=function(){this.isFullScreen()?this.m("vjs-fullscreen"):this.r("vjs-fullscreen")};t.Fb=function(a){u.log("Video Error",a)};
function N(a,c,d){if(a.f&&!a.f.aa)a.f.I(function(){this[c](d)});else try{a.f[c](d)}catch(e){throw u.log(e),e;}}function M(a,c){if(a.f&&a.f.aa)try{return a.f[c]()}catch(d){throw a.f[c]===b?u.log("Video.js: "+c+" method not defined for "+a.ya+" playback technology.",d):"TypeError"==d.name?(u.log("Video.js: "+c+" unavailable on "+a.ya+" playback technology element.",d),a.f.aa=l):u.log(d),d;}}t.play=function(){N(this,"play");return this};t.pause=function(){N(this,"pause");return this};
t.paused=function(){return M(this,"paused")===l?l:f};t.currentTime=function(a){return a!==b?(N(this,"setCurrentTime",a),this.Db&&this.k("timeupdate"),this):this.u.currentTime=M(this,"currentTime")||0};t.duration=function(a){if(a!==b)return this.u.duration=parseFloat(a),this;this.u.duration===b&&this.sc();return this.u.duration||0};t.buffered=function(){var a=M(this,"buffered"),c=a.length-1,d=this.u.nb=this.u.nb||0;a&&(0<=c&&a.end(c)!==d)&&(d=a.end(c),this.u.nb=d);return u.tb(0,d)};
t.bufferedPercent=function(){return this.duration()?this.buffered().end(0)/this.duration():0};t.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.u.volume=a,N(this,"setVolume",a),u.zd(a),this;a=parseFloat(M(this,"volume"));return isNaN(a)?1:a};t.muted=function(a){return a!==b?(N(this,"setMuted",a),this):M(this,"muted")||l};t.Xa=function(){return M(this,"supportsFullScreen")||l};t.qc=l;t.isFullScreen=function(a){return a!==b?(this.qc=a,this):this.qc};
t.requestFullScreen=function(){var a=u.Ob.requestFullScreen;this.isFullScreen(f);a?(u.d(document,a.ub,u.bind(this,function(c){this.isFullScreen(document[a.isFullScreen]);this.isFullScreen()===l&&u.o(document,a.ub,arguments.callee);this.k("fullscreenchange")})),this.a[a.Lb]()):this.f.Xa()?N(this,"enterFullScreen"):(this.hd=f,this.$c=document.documentElement.style.overflow,u.d(document,"keydown",u.bind(this,this.lc)),document.documentElement.style.overflow="hidden",u.m(document.body,"vjs-full-window"),
this.k("enterFullWindow"),this.k("fullscreenchange"));return this};t.cancelFullScreen=function(){var a=u.Ob.requestFullScreen;this.isFullScreen(l);if(a)document[a.pb]();else this.f.Xa()?N(this,"exitFullScreen"):(O(this),this.k("fullscreenchange"));return this};t.lc=function(a){27===a.keyCode&&(this.isFullScreen()===f?this.cancelFullScreen():O(this))};
function O(a){a.hd=l;u.o(document,"keydown",a.lc);document.documentElement.style.overflow=a.$c;u.r(document.body,"vjs-full-window");a.k("exitFullWindow")}
t.src=function(a){if(a===b)return M(this,"src");if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.j.techOrder;d<e.length;d++){var g=u.Z(e[d]),h=window.videojs[g];if(h.isSupported())for(var k=0,p=c;k<p.length;k++){var n=p[k];if(h.canPlaySource(n)){c={source:n,f:g};break a}}}c=l}c?(a=c.source,c=c.f,c==this.ya?this.src(a):J(this,c,a)):(this.a.appendChild(u.e("p",{innerHTML:this.options().notSupportedMessage})),this.Aa())}else a instanceof Object?window.videojs[this.ya].canPlaySource(a)?this.src(a.src):
this.src([a]):(this.u.src=a,this.aa?(N(this,"src",a),"auto"==this.j.preload&&this.load(),this.j.autoplay&&this.play()):this.I(function(){this.src(a)}));return this};t.load=function(){N(this,"load");return this};t.currentSrc=function(){return M(this,"currentSrc")||this.u.src||""};t.Ta=function(a){return a!==b?(N(this,"setPreload",a),this.j.preload=a,this):M(this,"preload")};t.autoplay=function(a){return a!==b?(N(this,"setAutoplay",a),this.j.autoplay=a,this):M(this,"autoplay")};
t.loop=function(a){return a!==b?(N(this,"setLoop",a),this.j.loop=a,this):M(this,"loop")};t.poster=function(a){if(a===b)return this.vc;this.vc=a;N(this,"setPoster",a);this.k("posterchange")};t.controls=function(a){return a!==b?(a=!!a,this.sb!==a&&((this.sb=a)?(this.r("vjs-controls-disabled"),this.m("vjs-controls-enabled"),this.k("controlsenabled")):(this.r("vjs-controls-enabled"),this.m("vjs-controls-disabled"),this.k("controlsdisabled"))),this):this.sb};u.Player.prototype.Qb;t=u.Player.prototype;
t.usingNativeControls=function(a){return a!==b?(a=!!a,this.Qb!==a&&((this.Qb=a)?(this.m("vjs-using-native-controls"),this.k("usingnativecontrols")):(this.r("vjs-using-native-controls"),this.k("usingcustomcontrols"))),this):this.Qb};t.error=function(){return M(this,"error")};t.ended=function(){return M(this,"ended")};t.seeking=function(){return M(this,"seeking")};t.ja=f;t.reportUserActivity=function(){this.ja=f};t.Pb=f;
t.userActive=function(a){return a!==b?(a=!!a,a!==this.Pb&&((this.Pb=a)?(this.ja=f,this.r("vjs-user-inactive"),this.m("vjs-user-active"),this.k("useractive")):(this.ja=l,this.f&&this.f.U("mousemove",function(a){a.stopPropagation();a.preventDefault()}),this.r("vjs-user-active"),this.m("vjs-user-inactive"),this.k("userinactive"))),this):this.Pb};var P,Q,R;R=document.createElement("div");Q={};
R.Pd!==b?(Q.Lb="requestFullscreen",Q.pb="exitFullscreen",Q.ub="fullscreenchange",Q.isFullScreen="fullScreen"):(document.mozCancelFullScreen?(P="moz",Q.isFullScreen=P+"FullScreen",Q.Lb=P+"RequestFullScreen"):(P="webkit",Q.isFullScreen=P+"IsFullScreen",Q.Lb=P+"RequestFullscreen"),R[P+"RequestFullScreen"]&&(Q.pb=P+"CancelFullScreen"),Q.ub=P+"fullscreenchange");document[Q.pb]&&(u.Ob.requestFullScreen=Q);u.Ea=u.b.extend();
u.Ea.prototype.j={Ud:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},liveDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};u.Ea.prototype.e=function(){return u.e("div",{className:"vjs-control-bar"})};u.Wb=u.b.extend({i:function(a,c){u.b.call(this,a,c)}});
u.Wb.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-live-controls vjs-control"});this.C=u.e("div",{className:"vjs-live-display",innerHTML:'<span class="vjs-control-text">Stream Type </span>LIVE',"aria-live":"off"});a.appendChild(this.C);return a};u.Zb=u.q.extend({i:function(a,c){u.q.call(this,a,c);a.d("play",u.bind(this,this.Jb));a.d("pause",u.bind(this,this.Ib))}});t=u.Zb.prototype;t.pa="Play";t.Q=function(){return"vjs-play-control "+u.q.prototype.Q.call(this)};
t.p=function(){this.c.paused()?this.c.play():this.c.pause()};t.Jb=function(){u.r(this.a,"vjs-paused");u.m(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};t.Ib=function(){u.r(this.a,"vjs-playing");u.m(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};u.ab=u.b.extend({i:function(a,c){u.b.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});
u.ab.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.C=u.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(this.C);return a};u.ab.prototype.da=function(){var a=this.c.Wa?this.c.u.currentTime:this.c.currentTime();this.C.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.ua(a,this.c.duration())};
u.bb=u.b.extend({i:function(a,c){u.b.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});u.bb.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.C=u.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(this.C);return a};
u.bb.prototype.da=function(){var a=this.c.duration();a&&(this.C.innerHTML='<span class="vjs-control-text">Duration Time </span>'+u.ua(a))};u.dc=u.b.extend({i:function(a,c){u.b.call(this,a,c)}});u.dc.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};u.hb=u.b.extend({i:function(a,c){u.b.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});
u.hb.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.C=u.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(this.C);return a};u.hb.prototype.da=function(){this.c.duration()&&(this.C.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.ua(this.c.duration()-this.c.currentTime()))};
u.Fa=u.q.extend({i:function(a,c){u.q.call(this,a,c)}});u.Fa.prototype.pa="Fullscreen";u.Fa.prototype.Q=function(){return"vjs-fullscreen-control "+u.q.prototype.Q.call(this)};u.Fa.prototype.p=function(){this.c.isFullScreen()?(this.c.cancelFullScreen(),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.c.requestFullScreen(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};u.gb=u.b.extend({i:function(a,c){u.b.call(this,a,c)}});u.gb.prototype.j={children:{seekBar:{}}};
u.gb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};u.$b=u.O.extend({i:function(a,c){u.O.call(this,a,c);a.d("timeupdate",u.bind(this,this.Ba));a.I(u.bind(this,this.Ba))}});t=u.$b.prototype;t.j={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};t.uc="timeupdate";t.e=function(){return u.O.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};
t.Ba=function(){var a=this.c.Wa?this.c.u.currentTime:this.c.currentTime();this.a.setAttribute("aria-valuenow",u.round(100*this.xb(),2));this.a.setAttribute("aria-valuetext",u.ua(a,this.c.duration()))};t.xb=function(){return this.c.currentTime()/this.c.duration()};t.Sa=function(a){u.O.prototype.Sa.call(this,a);this.c.Wa=f;this.Kd=!this.c.paused();this.c.pause()};t.Gb=function(a){a=G(this,a)*this.c.duration();a==this.c.duration()&&(a-=0.1);this.c.currentTime(a)};
t.Hb=function(a){u.O.prototype.Hb.call(this,a);this.c.Wa=l;this.Kd&&this.c.play()};t.Ac=function(){this.c.currentTime(this.c.currentTime()+5)};t.zc=function(){this.c.currentTime(this.c.currentTime()-5)};u.eb=u.b.extend({i:function(a,c){u.b.call(this,a,c);a.d("progress",u.bind(this,this.update))}});u.eb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};
u.eb.prototype.update=function(){this.a.style&&(this.a.style.width=u.round(100*this.c.bufferedPercent(),2)+"%")};u.Yb=u.b.extend({i:function(a,c){u.b.call(this,a,c)}});u.Yb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};u.Ha=u.X.extend({i:function(a,c){u.X.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});u.Ha.prototype.defaultValue="00:00";
u.Ha.prototype.e=function(){return u.X.prototype.e.call(this,"div",{className:"vjs-seek-handle","aria-live":"off"})};u.Ha.prototype.da=function(){var a=this.c.Wa?this.c.u.currentTime:this.c.currentTime();this.a.innerHTML='<span class="vjs-control-text">'+u.ua(a,this.c.duration())+"</span>"};u.jb=u.b.extend({i:function(a,c){u.b.call(this,a,c);a.f&&(a.f.n&&a.f.n.volumeControl===l)&&this.m("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.f.n&&a.f.n.volumeControl===l?this.m("vjs-hidden"):this.r("vjs-hidden")}))}});
u.jb.prototype.j={children:{volumeBar:{}}};u.jb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};u.ib=u.O.extend({i:function(a,c){u.O.call(this,a,c);a.d("volumechange",u.bind(this,this.Ba));a.I(u.bind(this,this.Ba))}});t=u.ib.prototype;t.Ba=function(){this.a.setAttribute("aria-valuenow",u.round(100*this.c.volume(),2));this.a.setAttribute("aria-valuetext",u.round(100*this.c.volume(),2)+"%")};
t.j={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};t.uc="volumechange";t.e=function(){return u.O.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};t.Gb=function(a){this.c.muted()&&this.c.muted(l);this.c.volume(G(this,a))};t.xb=function(){return this.c.muted()?0:this.c.volume()};t.Ac=function(){this.c.volume(this.c.volume()+0.1)};t.zc=function(){this.c.volume(this.c.volume()-0.1)};
u.ec=u.b.extend({i:function(a,c){u.b.call(this,a,c)}});u.ec.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};u.kb=u.X.extend();u.kb.prototype.defaultValue="00:00";u.kb.prototype.e=function(){return u.X.prototype.e.call(this,"div",{className:"vjs-volume-handle"})};
u.ea=u.q.extend({i:function(a,c){u.q.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.f&&(a.f.n&&a.f.n.volumeControl===l)&&this.m("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.f.n&&a.f.n.volumeControl===l?this.m("vjs-hidden"):this.r("vjs-hidden")}))}});u.ea.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};
u.ea.prototype.p=function(){this.c.muted(this.c.muted()?l:f)};u.ea.prototype.update=function(){var a=this.c.volume(),c=3;0===a||this.c.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.c.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.r(this.a,"vjs-vol-"+a);u.m(this.a,"vjs-vol-"+c)};
u.na=u.S.extend({i:function(a,c){u.S.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.f&&(a.f.n&&a.f.n.Ec===l)&&this.m("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.f.n&&a.f.n.Ec===l?this.m("vjs-hidden"):this.r("vjs-hidden")}));this.m("vjs-menu-button")}});u.na.prototype.Ma=function(){var a=new u.ma(this.c,{Vc:"div"}),c=new u.ib(this.c,u.l.A({Jd:f},this.j.ae));a.V(c);return a};u.na.prototype.p=function(){u.ea.prototype.p.call(this);u.S.prototype.p.call(this)};
u.na.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-volume-menu-button vjs-menu-button vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.na.prototype.update=u.ea.prototype.update;u.Ga=u.q.extend({i:function(a,c){u.q.call(this,a,c);a.poster()&&this.src(a.poster());(!a.poster()||!a.controls())&&this.D();a.d("posterchange",u.bind(this,function(){this.src(a.poster())}));a.d("play",u.bind(this,this.D))}});var S="backgroundSize"in u.G.style;
u.Ga.prototype.e=function(){var a=u.e("div",{className:"vjs-poster",tabIndex:-1});S||a.appendChild(u.e("img"));return a};u.Ga.prototype.src=function(a){var c=this.v();a!==b&&(S?c.style.backgroundImage='url("'+a+'")':c.firstChild.src=a)};u.Ga.prototype.p=function(){this.B().controls()&&this.c.play()};
u.Xb=u.b.extend({i:function(a,c){u.b.call(this,a,c);a.d("canplay",u.bind(this,this.D));a.d("canplaythrough",u.bind(this,this.D));a.d("playing",u.bind(this,this.D));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.D));a.d("error",u.bind(this,this.show));a.d("ended",u.bind(this,this.D));a.d("waiting",u.bind(this,this.show))}});u.Xb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-loading-spinner"})};u.Za=u.q.extend();
u.Za.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:'<span aria-hidden="true"></span>',"aria-label":"play video"})};u.Za.prototype.p=function(){this.c.play()};
u.s=u.b.extend({i:function(a,c,d){c=c||{};c.xc=l;u.b.call(this,a,c,d);var e,g;g=this;e=this.B();a=function(){if(e.controls()&&!e.usingNativeControls()){var a;g.d("mousedown",g.p);g.d("touchstart",function(c){c.preventDefault();a=this.c.userActive()});g.d("touchmove",function(){a&&this.B().reportUserActivity()});F(g);g.d("tap",g.sd)}};c=u.bind(g,g.wd);this.I(a);e.d("controlsenabled",a);e.d("controlsdisabled",c)}});t=u.s.prototype;
t.wd=function(){this.o("tap");this.o("touchstart");this.o("touchmove");this.o("touchleave");this.o("touchcancel");this.o("touchend");this.o("click");this.o("mousedown")};t.p=function(a){0===a.button&&this.B().controls()&&(this.B().paused()?this.B().play():this.B().pause())};t.sd=function(){this.B().userActive(!this.B().userActive())};t.Mb=m();t.n={volumeControl:f,fullscreenResize:l,progressEvents:l,timeupdateEvents:l};u.media={};u.media.Ya="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function ea(){var a=u.media.Ya[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.Ya.length-1;0<=i;i--)u.s.prototype[u.media.Ya[i]]=ea();
u.h=u.s.extend({i:function(a,c,d){this.n.volumeControl=u.h.Uc();this.n.movingMediaElementInDOM=!u.Jc;this.n.fullscreenResize=f;u.s.call(this,a,c,d);for(d=u.h.cb.length-1;0<=d;d--)u.d(this.a,u.h.cb[d],u.bind(this.c,this.bd));(c=c.source)&&this.a.currentSrc===c.src&&0<this.a.networkState?a.k("loadstart"):c&&(this.a.src=c.src);if(u.bc&&a.options().nativeControlsForTouch!==l){var e,g,h,k;e=this;g=this.B();c=g.controls();e.a.controls=!!c;h=function(){e.a.controls=f};k=function(){e.a.controls=l};g.d("controlsenabled",
h);g.d("controlsdisabled",k);c=function(){g.o("controlsenabled",h);g.o("controlsdisabled",k)};e.d("dispose",c);g.d("usingcustomcontrols",c);g.usingNativeControls(f)}a.I(function(){this.M&&(this.j.autoplay&&this.paused())&&(delete this.M.poster,this.play())});this.Aa()}});t=u.h.prototype;t.dispose=function(){u.s.prototype.dispose.call(this)};
t.e=function(){var a=this.c,c=a.M,d;if(!c||this.n.movingMediaElementInDOM===l)c?(d=c.cloneNode(l),u.h.ic(c),c=d,a.M=j):c=u.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,u.yb(c,a.v());d=["autoplay","preload","loop","muted"];for(var e=d.length-1;0<=e;e--){var g=d[e];a.j[g]!==j&&(c[g]=a.j[g])}return c};t.bd=function(a){this.k(a);a.stopPropagation()};t.play=function(){this.a.play()};t.pause=function(){this.a.pause()};t.paused=function(){return this.a.paused};t.currentTime=function(){return this.a.currentTime};
t.yd=function(a){try{this.a.currentTime=a}catch(c){u.log(c,"Video is not ready. (Video.js)")}};t.duration=function(){return this.a.duration||0};t.buffered=function(){return this.a.buffered};t.volume=function(){return this.a.volume};t.Dd=function(a){this.a.volume=a};t.muted=function(){return this.a.muted};t.Bd=function(a){this.a.muted=a};t.width=function(){return this.a.offsetWidth};t.height=function(){return this.a.offsetHeight};
t.Xa=function(){return"function"==typeof this.a.webkitEnterFullScreen&&(/Android/.test(u.J)||!/Chrome|Mac OS X 10.5/.test(u.J))?f:l};t.jc=function(){var a=this.a;a.paused&&a.networkState<=a.Md?(this.a.play(),setTimeout(function(){a.pause();a.webkitEnterFullScreen()},0)):a.webkitEnterFullScreen()};t.cd=function(){this.a.webkitExitFullScreen()};t.src=function(a){this.a.src=a};t.load=function(){this.a.load()};t.currentSrc=function(){return this.a.currentSrc};t.poster=function(){return this.a.poster};
t.Mb=function(a){this.a.poster=a};t.Ta=function(){return this.a.Ta};t.Cd=function(a){this.a.Ta=a};t.autoplay=function(){return this.a.autoplay};t.xd=function(a){this.a.autoplay=a};t.controls=function(){return this.a.controls};t.loop=function(){return this.a.loop};t.Ad=function(a){this.a.loop=a};t.error=function(){return this.a.error};t.seeking=function(){return this.a.seeking};t.ended=function(){return this.a.ended};u.h.isSupported=function(){try{u.G.volume=0.5}catch(a){return l}return!!u.G.canPlayType};
u.h.ob=function(a){try{return!!u.G.canPlayType(a.type)}catch(c){return""}};u.h.Uc=function(){var a=u.G.volume;u.G.volume=a/2+0.1;return a!==u.G.volume};var T,fa=/^application\/(?:x-|vnd\.apple\.)mpegurl/i,ga=/^video\/mp4/i;
u.h.tc=function(){4<=u.Rb&&(T||(T=u.G.constructor.prototype.canPlayType),u.G.constructor.prototype.canPlayType=function(a){return a&&fa.test(a)?"maybe":T.call(this,a)});u.Nc&&(T||(T=u.G.constructor.prototype.canPlayType),u.G.constructor.prototype.canPlayType=function(a){return a&&ga.test(a)?"maybe":T.call(this,a)})};u.h.Id=function(){var a=u.G.constructor.prototype.canPlayType;u.G.constructor.prototype.canPlayType=T;T=j;return a};u.h.tc();u.h.cb="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
u.h.ic=function(a){if(a){a.player=j;for(a.parentNode&&a.parentNode.removeChild(a);a.hasChildNodes();)a.removeChild(a.firstChild);a.removeAttribute("src");if("function"===typeof a.load)try{a.load()}catch(c){}}};
u.g=u.s.extend({i:function(a,c,d){u.s.call(this,a,c,d);var e=c.source;d=c.parentEl;var g=this.a=u.e("div",{id:a.id()+"_temp_flash"}),h=a.id()+"_flash_api";a=a.j;var k=u.l.A({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.Ta,loop:a.loop,muted:a.muted},c.flashVars),p=u.l.A({wmode:"opaque",bgcolor:"#000000"},c.params),n=u.l.A({id:h,name:h,"class":"vjs-tech"},c.attributes),s;e&&(e.type&&u.g.kd(e.type)?
(a=u.g.Bc(e.src),k.rtmpConnection=encodeURIComponent(a.rb),k.rtmpStream=encodeURIComponent(a.Nb)):k.src=encodeURIComponent(u.mc(e.src)));this.setCurrentTime=function(a){s=a;this.a.vjs_setProperty("currentTime",a)};this.currentTime=function(){return this.seeking()?s:this.a.vjs_getProperty("currentTime")};u.yb(g,d);c.startTime&&this.I(function(){this.load();this.play();this.currentTime(c.startTime)});u.Vb&&this.I(function(){u.d(this.v(),"mousemove",u.bind(this,function(){this.B().k({type:"mousemove",
bubbles:l})}))});if(c.iFrameMode===f&&!u.Vb){var D=u.e("iframe",{id:h+"_iframe",name:h+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";u.d(D,"load",u.bind(this,function(){var a,d=D.contentWindow;a=D.contentDocument?D.contentDocument:D.contentWindow.document;a.write(u.g.nc(c.swf,k,p,n));d.player=this.c;d.ready=u.bind(this.c,function(c){var d=this.f;d.a=a.getElementById(c);
u.g.qb(d)});d.events=u.bind(this.c,function(a,c){this&&"flash"===this.ya&&this.k(c)});d.errors=u.bind(this.c,function(a,c){u.log("Flash Error",c)})}));g.parentNode.replaceChild(D,g)}else u.g.ad(c.swf,g,k,p,n)}});t=u.g.prototype;t.dispose=function(){u.s.prototype.dispose.call(this)};t.play=function(){this.a.vjs_play()};t.pause=function(){this.a.vjs_pause()};
t.src=function(a){if(a===b)return this.currentSrc();u.g.jd(a)?(a=u.g.Bc(a),this.Wd(a.rb),this.Xd(a.Nb)):(a=u.mc(a),this.a.vjs_src(a));if(this.c.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};t.currentSrc=function(){var a=this.a.vjs_getProperty("currentSrc");if(a==j){var c=this.rtmpConnection(),d=this.rtmpStream();c&&d&&(a=u.g.Ed(c,d))}return a};t.load=function(){this.a.vjs_load()};t.poster=function(){this.a.vjs_getProperty("poster")};t.Mb=m();t.buffered=function(){return u.tb(0,this.a.vjs_getProperty("buffered"))};
t.Xa=r(l);t.jc=r(l);var U=u.g.prototype,V="rtmpConnection rtmpStream preload defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),W="error networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function ha(){var a=V[X],c=a.charAt(0).toUpperCase()+a.slice(1);U["set"+c]=function(c){return this.a.vjs_setProperty(a,c)}}
function Y(a){U[a]=function(){return this.a.vjs_getProperty(a)}}var X;for(X=0;X<V.length;X++)Y(V[X]),ha();for(X=0;X<W.length;X++)Y(W[X]);u.g.isSupported=function(){return 10<=u.g.version()[0]};u.g.ob=function(a){if(!a.type)return"";a=a.type.replace(/;.*/,"").toLowerCase();if(a in u.g.ed||a in u.g.Cc)return"maybe"};u.g.ed={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};u.g.Cc={"rtmp/mp4":"MP4","rtmp/flv":"FLV"};
u.g.onReady=function(a){a=u.v(a);var c=a.player||a.parentNode.player,d=c.f;a.player=c;d.a=a;u.g.qb(d)};u.g.qb=function(a){a.v().vjs_getProperty?a.Aa():setTimeout(function(){u.g.qb(a)},50)};u.g.onEvent=function(a,c){u.v(a).player.k(c)};u.g.onError=function(a,c){u.v(a).player.k("error");u.log("Flash Error",c,a)};
u.g.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
u.g.ad=function(a,c,d,e,g){a=u.g.nc(a,d,e,g);a=u.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var h=d.childNodes[0];setTimeout(function(){h.style.display="block"},1E3)};
u.g.nc=function(a,c,d,e){var g="",h="",k="";c&&u.l.sa(c,function(a,c){g+=a+"="+c+"&amp;"});d=u.l.A({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.l.sa(d,function(a,c){h+='<param name="'+a+'" value="'+c+'" />'});e=u.l.A({data:a,width:"100%",height:"100%"},e);u.l.sa(e,function(a,c){k+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+h+"</object>"};u.g.Ed=function(a,c){return a+"&"+c};
u.g.Bc=function(a){var c={rb:"",Nb:""};if(!a)return c;var d=a.indexOf("&"),e;-1!==d?e=d+1:(d=e=a.lastIndexOf("/")+1,0===d&&(d=e=a.length));c.rb=a.substring(0,d);c.Nb=a.substring(e,a.length);return c};u.g.kd=function(a){return a in u.g.Cc};u.g.Pc=/^rtmp[set]?:\/\//i;u.g.jd=function(a){return u.g.Pc.test(a)};
u.Oc=u.b.extend({i:function(a,c,d){u.b.call(this,a,c,d);if(!a.j.sources||0===a.j.sources.length){c=0;for(d=a.j.techOrder;c<d.length;c++){var e=u.Z(d[c]),g=window.videojs[e];if(g&&g.isSupported()){J(a,e);break}}}else a.src(a.j.sources)}});u.Player.prototype.textTracks=function(){return this.za=this.za||[]};
function ia(a,c,d,e,g){var h=a.za=a.za||[];g=g||{};g.kind=c;g.label=d;g.language=e;c=u.Z(c||"subtitles");var k=new window.videojs[c+"Track"](a,g);h.push(k);k.Na()&&a.I(function(){setTimeout(function(){k.show()},0)})}function ja(a,c,d){for(var e=a.za,g=0,h=e.length,k,p;g<h;g++)k=e[g],k.id()===c?(k.show(),p=k):d&&(k.H()==d&&0<k.mode())&&k.disable();(c=p?p.H():d?d:l)&&a.k(c+"trackchange")}
u.w=u.b.extend({i:function(a,c){u.b.call(this,a,c);this.R=c.id||"vjs_"+c.kind+"_"+c.language+"_"+u.t++;this.yc=c.src;this.Yc=c["default"]||c.dflt;this.Gd=c.title;this.Td=c.srclang;this.ld=c.label;this.$=[];this.lb=[];this.ha=this.ia=0;this.c.d("fullscreenchange",u.bind(this,this.Rc))}});t=u.w.prototype;t.H=q("F");t.src=q("yc");t.Na=q("Yc");t.title=q("Gd");t.label=q("ld");t.Wc=q("$");t.Qc=q("lb");t.readyState=q("ia");t.mode=q("ha");
t.Rc=function(){this.a.style.fontSize=this.c.isFullScreen()?140*(screen.width/this.c.width())+"%":""};t.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-"+this.F+" vjs-text-track"})};t.show=function(){ka(this);this.ha=2;u.b.prototype.show.call(this)};t.D=function(){ka(this);this.ha=1;u.b.prototype.D.call(this)};
t.disable=function(){2==this.ha&&this.D();this.c.o("timeupdate",u.bind(this,this.update,this.R));this.c.o("ended",u.bind(this,this.reset,this.R));this.reset();this.c.ga("textTrackDisplay").removeChild(this);this.ha=0};function ka(a){0===a.ia&&a.load();0===a.ha&&(a.c.d("timeupdate",u.bind(a,a.update,a.R)),a.c.d("ended",u.bind(a,a.reset,a.R)),("captions"===a.F||"subtitles"===a.F)&&a.c.ga("textTrackDisplay").V(a))}
t.load=function(){0===this.ia&&(this.ia=1,u.get(this.yc,u.bind(this,this.td),u.bind(this,this.Fb)))};t.Fb=function(a){this.error=a;this.ia=3;this.k("error")};t.td=function(a){var c,d;a=a.split("\n");for(var e="",g=1,h=a.length;g<h;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=u.trim(a[++g])):c=this.$.length;c={id:c,index:this.$.length};d=e.split(" --\x3e ");c.startTime=la(d[0]);c.ta=la(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.$.push(c)}this.ia=2;this.k("loaded")};
function la(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
t.update=function(){if(0<this.$.length){var a=this.c.currentTime();if(this.Kb===b||a<this.Kb||this.Pa<=a){var c=this.$,d=this.c.duration(),e=0,g=l,h=[],k,p,n,s;a>=this.Pa||this.Pa===b?s=this.vb!==b?this.vb:0:(g=f,s=this.Bb!==b?this.Bb:c.length-1);for(;;){n=c[s];if(n.ta<=a)e=Math.max(e,n.ta),n.Ja&&(n.Ja=l);else if(a<n.startTime){if(d=Math.min(d,n.startTime),n.Ja&&(n.Ja=l),!g)break}else g?(h.splice(0,0,n),p===b&&(p=s),k=s):(h.push(n),k===b&&(k=s),p=s),d=Math.min(d,n.ta),e=Math.max(e,n.startTime),n.Ja=
f;if(g)if(0===s)break;else s--;else if(s===c.length-1)break;else s++}this.lb=h;this.Pa=d;this.Kb=e;this.vb=k;this.Bb=p;a=this.lb;c="";d=0;for(e=a.length;d<e;d++)c+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=c;this.k("cuechange")}}};t.reset=function(){this.Pa=0;this.Kb=this.c.duration();this.Bb=this.vb=0};u.Tb=u.w.extend();u.Tb.prototype.F="captions";u.ac=u.w.extend();u.ac.prototype.F="subtitles";u.Ub=u.w.extend();u.Ub.prototype.F="chapters";
u.cc=u.b.extend({i:function(a,c,d){u.b.call(this,a,c,d);if(a.j.tracks&&0<a.j.tracks.length){c=this.c;a=a.j.tracks;for(var e=0;e<a.length;e++)d=a[e],ia(c,d.kind,d.label,d.language,d)}}});u.cc.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};u.Y=u.N.extend({i:function(a,c){var d=this.ca=c.track;c.label=d.label();c.selected=d.Na();u.N.call(this,a,c);this.c.d(d.H()+"trackchange",u.bind(this,this.update))}});
u.Y.prototype.p=function(){u.N.prototype.p.call(this);ja(this.c,this.ca.R,this.ca.H())};u.Y.prototype.update=function(){this.selected(2==this.ca.mode())};u.fb=u.Y.extend({i:function(a,c){c.track={H:function(){return c.kind},B:a,label:function(){return c.kind+" off"},Na:r(l),mode:r(l)};u.Y.call(this,a,c);this.selected(f)}});u.fb.prototype.p=function(){u.Y.prototype.p.call(this);ja(this.c,this.ca.R,this.ca.H())};
u.fb.prototype.update=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.H()==this.ca.H()&&2==e.mode()&&(g=l);this.selected(g)};u.T=u.S.extend({i:function(a,c){u.S.call(this,a,c);1>=this.L.length&&this.D()}});u.T.prototype.ra=function(){var a=[],c;a.push(new u.fb(this.c,{kind:this.F}));for(var d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.H()===this.F&&a.push(new u.Y(this.c,{track:c}));return a};
u.Ca=u.T.extend({i:function(a,c,d){u.T.call(this,a,c,d);this.a.setAttribute("aria-label","Captions Menu")}});u.Ca.prototype.F="captions";u.Ca.prototype.pa="Captions";u.Ca.prototype.className="vjs-captions-button";u.Ia=u.T.extend({i:function(a,c,d){u.T.call(this,a,c,d);this.a.setAttribute("aria-label","Subtitles Menu")}});u.Ia.prototype.F="subtitles";u.Ia.prototype.pa="Subtitles";u.Ia.prototype.className="vjs-subtitles-button";
u.Da=u.T.extend({i:function(a,c,d){u.T.call(this,a,c,d);this.a.setAttribute("aria-label","Chapters Menu")}});t=u.Da.prototype;t.F="chapters";t.pa="Chapters";t.className="vjs-chapters-button";t.ra=function(){for(var a=[],c,d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.H()===this.F&&a.push(new u.Y(this.c,{track:c}));return a};
t.Ma=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g,h=this.L=[];c<d;c++)if(e=a[c],e.H()==this.F&&e.Na()){if(2>e.readyState()){this.Qd=e;e.d("loaded",u.bind(this,this.Ma));return}g=e;break}a=this.va=new u.ma(this.c);a.fa().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.Z(this.F),Fd:-1}));if(g){e=g.$;for(var k,c=0,d=e.length;c<d;c++)k=e[c],k=new u.$a(this.c,{track:g,cue:k}),h.push(k),a.V(k)}0<this.L.length&&this.show();return a};
u.$a=u.N.extend({i:function(a,c){var d=this.ca=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.ta;u.N.call(this,a,c);d.d("cuechange",u.bind(this,this.update))}});u.$a.prototype.p=function(){u.N.prototype.p.call(this);this.c.currentTime(this.cue.startTime);this.update(this.cue.startTime)};u.$a.prototype.update=function(){var a=this.cue,c=this.c.currentTime();this.selected(a.startTime<=c&&c<a.ta)};
u.l.A(u.Ea.prototype.j.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var Z=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,c){function d(a,e){var k,p,n=a[e];if(n&&"object"===typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(p=d(n,k),p!==b?n[k]=p:delete n[k]);return c.call(a,e,n)}var e;a=String(a);Z.lastIndex=0;Z.test(a)&&(a=a.replace(Z,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
u.fc=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==j&&(a=u.JSON.parse(a||"{}"),videojs(c,a)));else{u.mb();break}else u.Fc||u.mb()};u.mb=function(){setTimeout(u.fc,1)};"complete"===document.readyState?u.Fc=f:u.U(window,"load",function(){u.Fc=f});u.mb();u.vd=function(a,c){u.Player.prototype[a]=c};var ma=this;ma.Ld=f;function $(a,c){var d=a.split("."),e=ma;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",u);$("_V_",u);$("videojs.options",u.options);$("videojs.players",u.wa);$("videojs.TOUCH_ENABLED",u.bc);$("videojs.cache",u.qa);$("videojs.Component",u.b);u.b.prototype.player=u.b.prototype.B;u.b.prototype.options=u.b.prototype.options;u.b.prototype.init=u.b.prototype.i;u.b.prototype.dispose=u.b.prototype.dispose;u.b.prototype.createEl=u.b.prototype.e;u.b.prototype.contentEl=u.b.prototype.fa;u.b.prototype.el=u.b.prototype.v;u.b.prototype.addChild=u.b.prototype.V;
u.b.prototype.getChild=u.b.prototype.ga;u.b.prototype.getChildById=u.b.prototype.fd;u.b.prototype.children=u.b.prototype.children;u.b.prototype.initChildren=u.b.prototype.pc;u.b.prototype.removeChild=u.b.prototype.removeChild;u.b.prototype.on=u.b.prototype.d;u.b.prototype.off=u.b.prototype.o;u.b.prototype.one=u.b.prototype.U;u.b.prototype.trigger=u.b.prototype.k;u.b.prototype.triggerReady=u.b.prototype.Aa;u.b.prototype.show=u.b.prototype.show;u.b.prototype.hide=u.b.prototype.D;
u.b.prototype.width=u.b.prototype.width;u.b.prototype.height=u.b.prototype.height;u.b.prototype.dimensions=u.b.prototype.Zc;u.b.prototype.ready=u.b.prototype.I;u.b.prototype.addClass=u.b.prototype.m;u.b.prototype.removeClass=u.b.prototype.r;u.b.prototype.buildCSSClass=u.b.prototype.Q;u.Player.prototype.ended=u.Player.prototype.ended;$("videojs.MediaLoader",u.Oc);$("videojs.TextTrackDisplay",u.cc);$("videojs.ControlBar",u.Ea);$("videojs.Button",u.q);$("videojs.PlayToggle",u.Zb);
$("videojs.FullscreenToggle",u.Fa);$("videojs.BigPlayButton",u.Za);$("videojs.LoadingSpinner",u.Xb);$("videojs.CurrentTimeDisplay",u.ab);$("videojs.DurationDisplay",u.bb);$("videojs.TimeDivider",u.dc);$("videojs.RemainingTimeDisplay",u.hb);$("videojs.LiveDisplay",u.Wb);$("videojs.Slider",u.O);$("videojs.ProgressControl",u.gb);$("videojs.SeekBar",u.$b);$("videojs.LoadProgressBar",u.eb);$("videojs.PlayProgressBar",u.Yb);$("videojs.SeekHandle",u.Ha);$("videojs.VolumeControl",u.jb);
$("videojs.VolumeBar",u.ib);$("videojs.VolumeLevel",u.ec);$("videojs.VolumeMenuButton",u.na);$("videojs.VolumeHandle",u.kb);$("videojs.MuteToggle",u.ea);$("videojs.PosterImage",u.Ga);$("videojs.Menu",u.ma);$("videojs.MenuItem",u.N);$("videojs.MenuButton",u.S);u.S.prototype.createItems=u.S.prototype.ra;u.T.prototype.createItems=u.T.prototype.ra;u.Da.prototype.createItems=u.Da.prototype.ra;$("videojs.SubtitlesButton",u.Ia);$("videojs.CaptionsButton",u.Ca);$("videojs.ChaptersButton",u.Da);
$("videojs.MediaTechController",u.s);u.s.prototype.features=u.s.prototype.n;u.s.prototype.n.volumeControl=u.s.prototype.n.Ec;u.s.prototype.n.fullscreenResize=u.s.prototype.n.Rd;u.s.prototype.n.progressEvents=u.s.prototype.n.Vd;u.s.prototype.n.timeupdateEvents=u.s.prototype.n.Yd;u.s.prototype.setPoster=u.s.prototype.Mb;$("videojs.Html5",u.h);u.h.Events=u.h.cb;u.h.isSupported=u.h.isSupported;u.h.canPlaySource=u.h.ob;u.h.patchCanPlayType=u.h.tc;u.h.unpatchCanPlayType=u.h.Id;
u.h.prototype.setCurrentTime=u.h.prototype.yd;u.h.prototype.setVolume=u.h.prototype.Dd;u.h.prototype.setMuted=u.h.prototype.Bd;u.h.prototype.setPreload=u.h.prototype.Cd;u.h.prototype.setAutoplay=u.h.prototype.xd;u.h.prototype.setLoop=u.h.prototype.Ad;u.h.prototype.enterFullScreen=u.h.prototype.jc;u.h.prototype.exitFullScreen=u.h.prototype.cd;$("videojs.Flash",u.g);u.g.isSupported=u.g.isSupported;u.g.canPlaySource=u.g.ob;u.g.onReady=u.g.onReady;$("videojs.TextTrack",u.w);u.w.prototype.label=u.w.prototype.label;
u.w.prototype.kind=u.w.prototype.H;u.w.prototype.mode=u.w.prototype.mode;u.w.prototype.cues=u.w.prototype.Wc;u.w.prototype.activeCues=u.w.prototype.Qc;$("videojs.CaptionsTrack",u.Tb);$("videojs.SubtitlesTrack",u.ac);$("videojs.ChaptersTrack",u.Ub);$("videojs.autoSetup",u.fc);$("videojs.plugin",u.vd);$("videojs.createTimeRange",u.tb);$("videojs.util",u.ka);u.ka.mergeOptions=u.ka.Eb;})();
