/*! Video.js v4.5.2 Copyright 2014 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */ 
(function() {var b=void 0,f=!0,j=null,l=!1;function m(){return function(){}}function p(a){return function(){return this[a]}}function r(a){return function(){return a}}var s;document.createElement("video");document.createElement("audio");document.createElement("track");function t(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(t.wa[a])return t.wa[a];a=t.v(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new t.Player(a,c,d)}
var videojs=t;window.Yd=window.Zd=t;t.Sb="4.5";t.Gc="https:"==document.location.protocol?"https://":"http://";t.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}},notSupportedMessage:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'};
"GENERATED_CDN_VSN"!==t.Sb&&(videojs.options.flash.swf=t.Gc+"vjs.zencdn.net/"+t.Sb+"/video-js.swf");t.wa={};"function"===typeof define&&define.amd?define([],function(){return videojs}):"object"===typeof exports&&"object"===typeof module&&(module.exports=videojs);t.la=t.CoreObject=m();
t.la.extend=function(a){var c,d;a=a||{};c=a.init||a.i||this.prototype.init||this.prototype.i||m();d=function(){c.apply(this,arguments)};d.prototype=t.l.create(this.prototype);d.prototype.constructor=d;d.extend=t.la.extend;d.create=t.la.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};t.la.create=function(){var a=t.l.create(this.prototype);this.apply(a,arguments);return a};
t.d=function(a,c,d){var e=t.getData(a);e.z||(e.z={});e.z[c]||(e.z[c]=[]);d.t||(d.t=t.t++);e.z[c].push(d);e.W||(e.disabled=l,e.W=function(c){if(!e.disabled){c=t.kc(c);var d=e.z[c.type];if(d)for(var d=d.slice(0),k=0,q=d.length;k<q&&!c.rc();k++)d[k].call(a,c)}});1==e.z[c].length&&(document.addEventListener?a.addEventListener(c,e.W,l):document.attachEvent&&a.attachEvent("on"+c,e.W))};
t.o=function(a,c,d){if(t.oc(a)){var e=t.getData(a);if(e.z)if(c){var g=e.z[c];if(g){if(d){if(d.t)for(e=0;e<g.length;e++)g[e].t===d.t&&g.splice(e--,1)}else e.z[c]=[];t.gc(a,c)}}else for(g in e.z)c=g,e.z[c]=[],t.gc(a,c)}};t.gc=function(a,c){var d=t.getData(a);0===d.z[c].length&&(delete d.z[c],document.removeEventListener?a.removeEventListener(c,d.W,l):document.detachEvent&&a.detachEvent("on"+c,d.W));t.zb(d.z)&&(delete d.z,delete d.W,delete d.disabled);t.zb(d)&&t.wc(a)};
t.kc=function(a){function c(){return f}function d(){return l}if(!a||!a.Ab){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&("layerY"!==g&&"keyboardEvent.keyLocation"!==g)&&("returnValue"==g&&e.preventDefault||(a[g]=e[g]));a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=l;a.gd=c;a.defaultPrevented=f};a.gd=d;a.defaultPrevented=l;a.stopPropagation=function(){e.stopPropagation&&
e.stopPropagation();a.cancelBubble=f;a.Ab=c};a.Ab=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&e.stopImmediatePropagation();a.rc=c;a.stopPropagation()};a.rc=d;if(a.clientX!=j){g=document.documentElement;var h=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=j&&(a.button=a.button&1?0:a.button&
4?1:a.button&2?2:0)}return a};t.k=function(a,c){var d=t.oc(a)?t.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=t.kc(c);d.W&&d.W.call(a,c);if(e&&!c.Ab()&&c.bubbles!==l)t.k(e,c);else if(!e&&!c.defaultPrevented&&(d=t.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=l}return!c.defaultPrevented};
t.U=function(a,c,d){function e(){t.o(a,c,e);d.apply(this,arguments)}e.t=d.t=d.t||t.t++;t.d(a,c,e)};var v=Object.prototype.hasOwnProperty;t.e=function(a,c){var d,e;d=document.createElement(a||"div");for(e in c)v.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};t.Z=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};t.l={};t.l.create=Object.create||function(a){function c(){}c.prototype=a;return new c};
t.l.sa=function(a,c,d){for(var e in a)v.call(a,e)&&c.call(d||this,e,a[e])};t.l.A=function(a,c){if(!c)return a;for(var d in c)v.call(c,d)&&(a[d]=c[d]);return a};t.l.Xc=function(a,c){var d,e,g;a=t.l.copy(a);for(d in c)v.call(c,d)&&(e=a[d],g=c[d],a[d]=t.l.Oa(e)&&t.l.Oa(g)?t.l.Xc(e,g):c[d]);return a};t.l.copy=function(a){return t.l.A({},a)};t.l.Oa=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};
t.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.t||(c.t=t.t++);e.t=d?d+"_"+c.t:c.t;return e};t.qa={};t.t=1;t.expando="vdata"+(new Date).getTime();t.getData=function(a){var c=a[t.expando];c||(c=a[t.expando]=t.t++,t.qa[c]={});return t.qa[c]};t.oc=function(a){a=a[t.expando];return!(!a||t.zb(t.qa[a]))};t.wc=function(a){var c=a[t.expando];if(c){delete t.qa[c];try{delete a[t.expando]}catch(d){a.removeAttribute?a.removeAttribute(t.expando):a[t.expando]=j}}};
t.zb=function(a){for(var c in a)if(a[c]!==j)return l;return f};t.m=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};t.r=function(a,c){var d,e;if(-1!=a.className.indexOf(c)){d=a.className.split(" ");for(e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};t.G=t.e("video");t.J=navigator.userAgent;t.Lc=/iPhone/i.test(t.J);t.Kc=/iPad/i.test(t.J);t.Mc=/iPod/i.test(t.J);t.Jc=t.Lc||t.Kc||t.Mc;var aa=t,w;var x=t.J.match(/OS (\d+)_/i);
w=x&&x[1]?x[1]:b;aa.Md=w;t.Ic=/Android/i.test(t.J);var ba=t,y;var z=t.J.match(/Android (\d+)(?:\.(\d+))?(?:\.(\d+))*/i),A,B;z?(A=z[1]&&parseFloat(z[1]),B=z[2]&&parseFloat(z[2]),y=A&&B?parseFloat(z[1]+"."+z[2]):A?A:j):y=j;ba.Rb=y;t.Nc=t.Ic&&/webkit/i.test(t.J)&&2.3>t.Rb;t.Vb=/Firefox/i.test(t.J);t.Nd=/Chrome/i.test(t.J);t.bc=!!("ontouchstart"in window||window.Hc&&document instanceof window.Hc);
t.wb=function(a){var c,d,e,g;c={};if(a&&a.attributes&&0<a.attributes.length){d=a.attributes;for(var h=d.length-1;0<=h;h--){e=d[h].name;g=d[h].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==j?f:l;c[e]=g}}return c};
t.Rd=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};t.yb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};t.Ob={};t.v=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
t.ua=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),h=Math.floor(c/60%60),k=Math.floor(c/3600);if(isNaN(a)||Infinity===a)g=e=d="-";g=0<g||0<k?g+":":"";return g+(((g||10<=h)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};t.Tc=function(){document.body.focus();document.onselectstart=r(l)};t.Gd=function(){document.onselectstart=r(f)};t.trim=function(a){return(a+"").replace(/^\s+|\s+$/g,"")};t.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};
t.tb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
t.get=function(a,c,d,e){var g,h,k;d=d||m();"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});h=new XMLHttpRequest;k=t.e("a",{href:a});k.origin!==window.location.origin&&window.XDomainRequest&&!("withCredentials"in h)?
(h=new window.XDomainRequest,h.onload=function(){c(h.responseText)},h.onerror=d,h.onprogress=m(),h.ontimeout=d):(g="file:"==k.protocol||"file:"==window.location.protocol,h.onreadystatechange=function(){4===h.readyState&&(200===h.status||g&&0===h.status?c(h.responseText):d(h.responseText))});try{h.open("GET",a,f),e&&(h.withCredentials=f)}catch(q){d(q);return}try{h.send()}catch(n){d(n)}};
t.yd=function(a){try{var c=window.localStorage||l;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?t.log("LocalStorage Full (VideoJS)",d):18==d.code?t.log("LocalStorage not allowed (VideoJS)",d):t.log("LocalStorage Error (VideoJS)",d)}};t.mc=function(a){a.match(/^https?:\/\//)||(a=t.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};t.log=function(){t.log.history=t.log.history||[];t.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};
t.dd=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:t.round(c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0)),top:t.round(c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0))}};t.ka={};t.ka.Eb=function(a,c){var d,e,g;a=t.l.copy(a);for(d in c)c.hasOwnProperty(d)&&(e=a[d],g=c[d],a[d]=t.l.Oa(e)&&t.l.Oa(g)?t.ka.Eb(e,g):c[d]);return a};
t.b=t.la.extend({i:function(a,c,d){this.c=a;this.j=t.l.copy(this.j);c=this.options(c);this.R=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+t.t++);this.md=c.name||j;this.a=c.el||this.e();this.K=[];this.Ka={};this.La={};this.pc();this.I(d);if(c.xc!==l){var e,g;e=t.bind(this.B(),this.B().reportUserActivity);this.d("touchstart",function(){e();clearInterval(g);g=setInterval(e,250)});a=function(){e();clearInterval(g)};this.d("touchmove",e);this.d("touchend",a);this.d("touchcancel",a)}}});s=t.b.prototype;
s.dispose=function(){this.k({type:"dispose",bubbles:l});if(this.K)for(var a=this.K.length-1;0<=a;a--)this.K[a].dispose&&this.K[a].dispose();this.La=this.Ka=this.K=j;this.o();this.a.parentNode&&this.a.parentNode.removeChild(this.a);t.wc(this.a);this.a=j};s.c=f;s.B=p("c");s.options=function(a){return a===b?this.j:this.j=t.ka.Eb(this.j,a)};s.e=function(a,c){return t.e(a,c)};s.v=p("a");s.fa=function(){return this.C||this.a};s.id=p("R");s.name=p("md");s.children=p("K");s.fd=function(a){return this.Ka[a]};
s.ga=function(a){return this.La[a]};s.V=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||t.Z(e),c.name=e,d=new window.videojs[d](this.c||this,c)):d=a;this.K.push(d);"function"===typeof d.id&&(this.Ka[d.id()]=d);(e=e||d.name&&d.name())&&(this.La[e]=d);"function"===typeof d.el&&d.el()&&this.fa().appendChild(d.el());return d};
s.removeChild=function(a){"string"===typeof a&&(a=this.ga(a));if(a&&this.K){for(var c=l,d=this.K.length-1;0<=d;d--)if(this.K[d]===a){c=f;this.K.splice(d,1);break}c&&(this.Ka[a.id]=j,this.La[a.name]=j,(c=a.v())&&c.parentNode===this.fa()&&this.fa().removeChild(a.v()))}};s.pc=function(){var a,c,d,e;a=this;if(c=this.options().children)if(c instanceof Array)for(var g=0;g<c.length;g++)d=c[g],"string"==typeof d?(e=d,d={}):e=d.name,a[e]=a.V(e,d);else t.l.sa(c,function(c,d){d!==l&&(a[c]=a.V(c,d))})};s.Q=r("");
s.d=function(a,c){t.d(this.a,a,t.bind(this,c));return this};s.o=function(a,c){t.o(this.a,a,c);return this};s.U=function(a,c){t.U(this.a,a,t.bind(this,c));return this};s.k=function(a,c){t.k(this.a,a,c);return this};s.I=function(a){a&&(this.aa?a.call(this):(this.Va===b&&(this.Va=[]),this.Va.push(a)));return this};s.Aa=function(){this.aa=f;var a=this.Va;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.Va=[];this.k("ready")}};s.m=function(a){t.m(this.a,a);return this};
s.r=function(a){t.r(this.a,a);return this};s.show=function(){this.a.style.display="block";return this};s.D=function(){this.a.style.display="none";return this};function C(a){a.r("vjs-lock-showing")}s.disable=function(){this.D();this.show=m()};s.width=function(a,c){return E(this,"width",a,c)};s.height=function(a,c){return E(this,"height",a,c)};s.Zc=function(a,c){return this.width(a,f).height(c)};
function E(a,c,d,e){if(d!==b)return a.a.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.k("resize"),a;if(!a.a)return 0;d=a.a.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+t.Z(c)],10)}
function F(a){var c,d,e,g,h,k,q,n;c=0;d=j;a.d("touchstart",function(a){1===a.touches.length&&(d=a.touches[0],c=(new Date).getTime(),g=f)});a.d("touchmove",function(a){1<a.touches.length?g=l:d&&(k=a.touches[0].pageX-d.pageX,q=a.touches[0].pageY-d.pageY,n=Math.sqrt(k*k+q*q),22<n&&(g=l))});h=function(){g=l};a.d("touchleave",h);a.d("touchcancel",h);a.d("touchend",function(a){d=j;g===f&&(e=(new Date).getTime()-c,250>e&&(a.preventDefault(),this.k("tap")))})}
t.q=t.b.extend({i:function(a,c){t.b.call(this,a,c);F(this);this.d("tap",this.p);this.d("click",this.p);this.d("focus",this.Ra);this.d("blur",this.Qa)}});s=t.q.prototype;s.e=function(a,c){c=t.l.A({className:this.Q(),innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">'+(this.pa||"Need Text")+"</span></div>",role:"button","aria-live":"polite",tabIndex:0},c);return t.b.prototype.e.call(this,a,c)};s.Q=function(){return"vjs-control "+t.b.prototype.Q.call(this)};s.p=m();
s.Ra=function(){t.d(document,"keyup",t.bind(this,this.ba))};s.ba=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.p()};s.Qa=function(){t.o(document,"keyup",t.bind(this,this.ba))};
t.O=t.b.extend({i:function(a,c){t.b.call(this,a,c);this.Sc=this.ga(this.j.barName);this.handle=this.ga(this.j.handleName);this.d("mousedown",this.Sa);this.d("touchstart",this.Sa);this.d("focus",this.Ra);this.d("blur",this.Qa);this.d("click",this.p);this.c.d("controlsvisible",t.bind(this,this.update));a.d(this.uc,t.bind(this,this.update));this.P={}}});s=t.O.prototype;
s.e=function(a,c){c=c||{};c.className+=" vjs-slider";c=t.l.A({role:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return t.b.prototype.e.call(this,a,c)};s.Sa=function(a){a.preventDefault();t.Tc();this.P.move=t.bind(this,this.Gb);this.P.end=t.bind(this,this.Hb);t.d(document,"mousemove",this.P.move);t.d(document,"mouseup",this.P.end);t.d(document,"touchmove",this.P.move);t.d(document,"touchend",this.P.end);this.Gb(a)};
s.Hb=function(){t.Gd();t.o(document,"mousemove",this.P.move,l);t.o(document,"mouseup",this.P.end,l);t.o(document,"touchmove",this.P.move,l);t.o(document,"touchend",this.P.end,l);this.update()};s.update=function(){if(this.a){var a,c=this.xb(),d=this.handle,e=this.Sc;isNaN(c)&&(c=0);a=c;if(d){a=this.a.offsetWidth;var g=d.v().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.v().style.left=t.round(100*c,2)+"%"}e.v().style.width=t.round(100*a,2)+"%"}};
function G(a,c){var d,e,g,h;d=a.a;e=t.dd(d);h=g=d.offsetWidth;d=a.handle;if(a.j.Id)return h=e.top,e=c.changedTouches?c.changedTouches[0].pageY:c.pageY,d&&(d=d.v().offsetHeight,h+=d/2,g-=d),Math.max(0,Math.min(1,(h-e+g)/g));g=e.left;e=c.changedTouches?c.changedTouches[0].pageX:c.pageX;d&&(d=d.v().offsetWidth,g+=d/2,h-=d);return Math.max(0,Math.min(1,(e-g)/h))}s.Ra=function(){t.d(document,"keyup",t.bind(this,this.ba))};
s.ba=function(a){37==a.which?(a.preventDefault(),this.zc()):39==a.which&&(a.preventDefault(),this.Ac())};s.Qa=function(){t.o(document,"keyup",t.bind(this,this.ba))};s.p=function(a){a.stopImmediatePropagation();a.preventDefault()};t.X=t.b.extend();t.X.prototype.defaultValue=0;t.X.prototype.e=function(a,c){c=c||{};c.className+=" vjs-slider-handle";c=t.l.A({innerHTML:'<span class="vjs-control-text">'+this.defaultValue+"</span>"},c);return t.b.prototype.e.call(this,"div",c)};t.ma=t.b.extend();
function ca(a,c){a.V(c);c.d("click",t.bind(a,function(){C(this)}))}t.ma.prototype.e=function(){var a=this.options().Vc||"ul";this.C=t.e(a,{className:"vjs-menu-content"});a=t.b.prototype.e.call(this,"div",{append:this.C,className:"vjs-menu"});a.appendChild(this.C);t.d(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};t.N=t.q.extend({i:function(a,c){t.q.call(this,a,c);this.selected(c.selected)}});
t.N.prototype.e=function(a,c){return t.q.prototype.e.call(this,"li",t.l.A({className:"vjs-menu-item",innerHTML:this.j.label},c))};t.N.prototype.p=function(){this.selected(f)};t.N.prototype.selected=function(a){a?(this.m("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.r("vjs-selected"),this.a.setAttribute("aria-selected",l))};
t.S=t.q.extend({i:function(a,c){t.q.call(this,a,c);this.va=this.Ma();this.V(this.va);this.L&&0===this.L.length&&this.D();this.d("keyup",this.ba);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}});s=t.S.prototype;s.oa=l;s.Ma=function(){var a=new t.ma(this.c);this.options().title&&a.fa().appendChild(t.e("li",{className:"vjs-menu-title",innerHTML:t.Z(this.options().title),Ed:-1}));if(this.L=this.createItems())for(var c=0;c<this.L.length;c++)ca(a,this.L[c]);return a};
s.ra=m();s.Q=function(){return this.className+" vjs-menu-button "+t.q.prototype.Q.call(this)};s.Ra=m();s.Qa=m();s.p=function(){this.U("mouseout",t.bind(this,function(){C(this.va);this.a.blur()}));this.oa?H(this):I(this)};s.ba=function(a){a.preventDefault();32==a.which||13==a.which?this.oa?H(this):I(this):27==a.which&&this.oa&&H(this)};function I(a){a.oa=f;a.va.m("vjs-lock-showing");a.a.setAttribute("aria-pressed",f);a.L&&0<a.L.length&&a.L[0].v().focus()}
function H(a){a.oa=l;C(a.va);a.a.setAttribute("aria-pressed",l)}
t.Player=t.b.extend({i:function(a,c,d){this.M=a;a.id=a.id||"vjs_video_"+t.t++;c=t.l.A(da(a),c);this.u={};this.vc=c.poster;this.sb=c.controls;a.controls=l;c.xc=l;t.b.call(this,this,c,d);this.controls()?this.m("vjs-controls-enabled"):this.m("vjs-controls-disabled");this.d("loadstart",this.qd);this.d("ended",this.nd);this.d("play",this.Jb);this.d("firstplay",this.od);this.d("pause",this.Ib);this.d("progress",this.rd);this.d("durationchange",this.sc);this.d("error",this.Fb);this.d("fullscreenchange",
this.pd);t.wa[this.R]=this;c.plugins&&t.l.sa(c.plugins,function(a,c){this[a](c)},this);var e,g,h,k,q,n;e=t.bind(this,this.reportUserActivity);this.d("mousedown",function(){e();clearInterval(g);g=setInterval(e,250)});this.d("mousemove",function(a){if(a.screenX!=q||a.screenY!=n)q=a.screenX,n=a.screenY,e()});this.d("mouseup",function(){e();clearInterval(g)});this.d("keydown",e);this.d("keyup",e);h=setInterval(t.bind(this,function(){this.ja&&(this.ja=l,this.userActive(f),clearTimeout(k),k=setTimeout(t.bind(this,
function(){this.ja||this.userActive(l)}),2E3))}),250);this.d("dispose",function(){clearInterval(h);clearTimeout(k)})}});s=t.Player.prototype;s.j=t.options;s.dispose=function(){this.k("dispose");this.o("dispose");t.wa[this.R]=j;this.M&&this.M.player&&(this.M.player=j);this.a&&this.a.player&&(this.a.player=j);clearInterval(this.Ua);this.xa();this.f&&this.f.dispose();t.b.prototype.dispose.call(this)};
function da(a){var c={sources:[],tracks:[]};t.l.A(c,t.wb(a));if(a.hasChildNodes()){var d,e,g,h;a=a.childNodes;g=0;for(h=a.length;g<h;g++)d=a[g],e=d.nodeName.toLowerCase(),"source"===e?c.sources.push(t.wb(d)):"track"===e&&c.tracks.push(t.wb(d))}return c}
s.e=function(){var a=this.a=t.b.prototype.e.call(this,"div"),c=this.M;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes()){var d,e,g,h,k;d=c.childNodes;e=d.length;for(k=[];e--;)g=d[e],h=g.nodeName.toLowerCase(),"track"===h&&k.push(g);for(d=0;d<k.length;d++)c.removeChild(k[d])}a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.m("vjs-paused");this.width(this.j.width,f);this.height(this.j.height,f);c.parentNode&&c.parentNode.insertBefore(a,
c);t.yb(c,a);return a};
function J(a,c,d){a.f&&(a.aa=l,a.f.dispose(),a.Cb&&(a.Cb=l,clearInterval(a.Ua)),a.Db&&K(a),a.f=l);"Html5"!==c&&a.M&&(t.h.ic(a.M),a.M=j);a.ya=c;a.aa=l;var e=t.l.A({source:d,parentEl:a.a},a.j[c.toLowerCase()]);d&&(d.src==a.u.src&&0<a.u.currentTime&&(e.startTime=a.u.currentTime),a.u.src=d.src);a.f=new window.videojs[c](a,e);a.f.I(function(){this.c.Aa();if(!this.n.progressEvents){var a=this.c;a.Cb=f;a.Ua=setInterval(t.bind(a,function(){this.u.nb<this.buffered().end(0)?this.k("progress"):1==this.bufferedPercent()&&
(clearInterval(this.Ua),this.k("progress"))}),500);a.f&&a.f.U("progress",function(){this.n.progressEvents=f;var a=this.c;a.Cb=l;clearInterval(a.Ua)})}this.n.timeupdateEvents||(a=this.c,a.Db=f,a.d("play",a.Dc),a.d("pause",a.xa),a.f&&a.f.U("timeupdate",function(){this.n.timeupdateEvents=f;K(this.c)}))})}function K(a){a.Db=l;a.xa();a.o("play",a.Dc);a.o("pause",a.xa)}s.Dc=function(){this.hc&&this.xa();this.hc=setInterval(t.bind(this,function(){this.k("timeupdate")}),250)};
s.xa=function(){clearInterval(this.hc);this.k("timeupdate")};s.qd=function(){this.o("play",L);this.U("play",L);t.r(this.a,"vjs-has-started")};function L(a){t.k(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())}s.Jb=function(){t.r(this.a,"vjs-paused");t.m(this.a,"vjs-playing")};s.od=function(){this.j.starttime&&this.currentTime(this.j.starttime);this.m("vjs-has-started")};s.Ib=function(){t.r(this.a,"vjs-playing");t.m(this.a,"vjs-paused")};
s.rd=function(){1==this.bufferedPercent()&&this.k("loadedalldata")};s.nd=function(){this.j.loop&&(this.currentTime(0),this.play())};s.sc=function(){var a=M(this,"duration");a&&(0>a&&(a=Infinity),this.duration(a),Infinity===a?this.m("vjs-live"):this.r("vjs-live"))};s.pd=function(){this.isFullScreen()?this.m("vjs-fullscreen"):this.r("vjs-fullscreen")};s.Fb=function(a){t.log("Video Error",a)};
function N(a,c,d){if(a.f&&!a.f.aa)a.f.I(function(){this[c](d)});else try{a.f[c](d)}catch(e){throw t.log(e),e;}}function M(a,c){if(a.f&&a.f.aa)try{return a.f[c]()}catch(d){throw a.f[c]===b?t.log("Video.js: "+c+" method not defined for "+a.ya+" playback technology.",d):"TypeError"==d.name?(t.log("Video.js: "+c+" unavailable on "+a.ya+" playback technology element.",d),a.f.aa=l):t.log(d),d;}}s.play=function(){N(this,"play");return this};s.pause=function(){N(this,"pause");return this};
s.paused=function(){return M(this,"paused")===l?l:f};s.currentTime=function(a){return a!==b?(N(this,"setCurrentTime",a),this.Db&&this.k("timeupdate"),this):this.u.currentTime=M(this,"currentTime")||0};s.duration=function(a){if(a!==b)return this.u.duration=parseFloat(a),this;this.u.duration===b&&this.sc();return this.u.duration||0};s.buffered=function(){var a=M(this,"buffered"),c=a.length-1,d=this.u.nb=this.u.nb||0;a&&(0<=c&&a.end(c)!==d)&&(d=a.end(c),this.u.nb=d);return t.tb(0,d)};
s.bufferedPercent=function(){return this.duration()?this.buffered().end(0)/this.duration():0};s.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.u.volume=a,N(this,"setVolume",a),t.yd(a),this;a=parseFloat(M(this,"volume"));return isNaN(a)?1:a};s.muted=function(a){return a!==b?(N(this,"setMuted",a),this):M(this,"muted")||l};s.Xa=function(){return M(this,"supportsFullScreen")||l};s.qc=l;s.isFullScreen=function(a){return a!==b?(this.qc=a,this):this.qc};
s.requestFullScreen=function(){var a=t.Ob.requestFullScreen;this.isFullScreen(f);a?(t.d(document,a.ub,t.bind(this,function(c){this.isFullScreen(document[a.isFullScreen]);this.isFullScreen()===l&&t.o(document,a.ub,arguments.callee);this.k("fullscreenchange")})),this.a[a.Lb]()):this.f.Xa()?N(this,"enterFullScreen"):(this.hd=f,this.$c=document.documentElement.style.overflow,t.d(document,"keydown",t.bind(this,this.lc)),document.documentElement.style.overflow="hidden",t.m(document.body,"vjs-full-window"),
this.k("enterFullWindow"),this.k("fullscreenchange"));return this};s.cancelFullScreen=function(){var a=t.Ob.requestFullScreen;this.isFullScreen(l);if(a)document[a.pb]();else this.f.Xa()?N(this,"exitFullScreen"):(O(this),this.k("fullscreenchange"));return this};s.lc=function(a){27===a.keyCode&&(this.isFullScreen()===f?this.cancelFullScreen():O(this))};
function O(a){a.hd=l;t.o(document,"keydown",a.lc);document.documentElement.style.overflow=a.$c;t.r(document.body,"vjs-full-window");a.k("exitFullWindow")}
s.src=function(a){if(a===b)return M(this,"src");if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.j.techOrder;d<e.length;d++){var g=t.Z(e[d]),h=window.videojs[g];if(h.isSupported())for(var k=0,q=c;k<q.length;k++){var n=q[k];if(h.canPlaySource(n)){c={source:n,f:g};break a}}}c=l}c?(a=c.source,c=c.f,c==this.ya?this.src(a):J(this,c,a)):(this.a.appendChild(t.e("p",{innerHTML:this.options().notSupportedMessage})),this.Aa())}else a instanceof Object?window.videojs[this.ya].canPlaySource(a)?this.src(a.src):
this.src([a]):(this.u.src=a,this.aa?(N(this,"src",a),"auto"==this.j.preload&&this.load(),this.j.autoplay&&this.play()):this.I(function(){this.src(a)}));return this};s.load=function(){N(this,"load");return this};s.currentSrc=function(){return M(this,"currentSrc")||this.u.src||""};s.Ta=function(a){return a!==b?(N(this,"setPreload",a),this.j.preload=a,this):M(this,"preload")};s.autoplay=function(a){return a!==b?(N(this,"setAutoplay",a),this.j.autoplay=a,this):M(this,"autoplay")};
s.loop=function(a){return a!==b?(N(this,"setLoop",a),this.j.loop=a,this):M(this,"loop")};s.poster=function(a){if(a===b)return this.vc;this.vc=a;N(this,"setPoster",a);this.k("posterchange")};s.controls=function(a){return a!==b?(a=!!a,this.sb!==a&&((this.sb=a)?(this.r("vjs-controls-disabled"),this.m("vjs-controls-enabled"),this.k("controlsenabled")):(this.r("vjs-controls-enabled"),this.m("vjs-controls-disabled"),this.k("controlsdisabled"))),this):this.sb};t.Player.prototype.Qb;s=t.Player.prototype;
s.usingNativeControls=function(a){return a!==b?(a=!!a,this.Qb!==a&&((this.Qb=a)?(this.m("vjs-using-native-controls"),this.k("usingnativecontrols")):(this.r("vjs-using-native-controls"),this.k("usingcustomcontrols"))),this):this.Qb};s.error=function(){return M(this,"error")};s.ended=function(){return M(this,"ended")};s.seeking=function(){return M(this,"seeking")};s.ja=f;s.reportUserActivity=function(){this.ja=f};s.Pb=f;
s.userActive=function(a){return a!==b?(a=!!a,a!==this.Pb&&((this.Pb=a)?(this.ja=f,this.r("vjs-user-inactive"),this.m("vjs-user-active"),this.k("useractive")):(this.ja=l,this.f&&this.f.U("mousemove",function(a){a.stopPropagation();a.preventDefault()}),this.r("vjs-user-active"),this.m("vjs-user-inactive"),this.k("userinactive"))),this):this.Pb};var P,Q,R;R=document.createElement("div");Q={};
R.Od!==b?(Q.Lb="requestFullscreen",Q.pb="exitFullscreen",Q.ub="fullscreenchange",Q.isFullScreen="fullScreen"):(document.mozCancelFullScreen?(P="moz",Q.isFullScreen=P+"FullScreen",Q.Lb=P+"RequestFullScreen"):(P="webkit",Q.isFullScreen=P+"IsFullScreen",Q.Lb=P+"RequestFullscreen"),R[P+"RequestFullScreen"]&&(Q.pb=P+"CancelFullScreen"),Q.ub=P+"fullscreenchange");document[Q.pb]&&(t.Ob.requestFullScreen=Q);t.Ea=t.b.extend();
t.Ea.prototype.j={Td:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},liveDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};t.Ea.prototype.e=function(){return t.e("div",{className:"vjs-control-bar"})};t.Wb=t.b.extend({i:function(a,c){t.b.call(this,a,c)}});
t.Wb.prototype.e=function(){var a=t.b.prototype.e.call(this,"div",{className:"vjs-live-controls vjs-control"});this.C=t.e("div",{className:"vjs-live-display",innerHTML:'<span class="vjs-control-text">Stream Type </span>LIVE',"aria-live":"off"});a.appendChild(this.C);return a};t.Zb=t.q.extend({i:function(a,c){t.q.call(this,a,c);a.d("play",t.bind(this,this.Jb));a.d("pause",t.bind(this,this.Ib))}});s=t.Zb.prototype;s.pa="Play";s.Q=function(){return"vjs-play-control "+t.q.prototype.Q.call(this)};
s.p=function(){this.c.paused()?this.c.play():this.c.pause()};s.Jb=function(){t.r(this.a,"vjs-paused");t.m(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};s.Ib=function(){t.r(this.a,"vjs-playing");t.m(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};t.ab=t.b.extend({i:function(a,c){t.b.call(this,a,c);a.d("timeupdate",t.bind(this,this.da))}});
t.ab.prototype.e=function(){var a=t.b.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.C=t.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(this.C);return a};t.ab.prototype.da=function(){var a=this.c.Wa?this.c.u.currentTime:this.c.currentTime();this.C.innerHTML='<span class="vjs-control-text">Current Time </span>'+t.ua(a,this.c.duration())};
t.bb=t.b.extend({i:function(a,c){t.b.call(this,a,c);a.d("timeupdate",t.bind(this,this.da))}});t.bb.prototype.e=function(){var a=t.b.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.C=t.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(this.C);return a};
t.bb.prototype.da=function(){var a=this.c.duration();a&&(this.C.innerHTML='<span class="vjs-control-text">Duration Time </span>'+t.ua(a))};t.dc=t.b.extend({i:function(a,c){t.b.call(this,a,c)}});t.dc.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};t.hb=t.b.extend({i:function(a,c){t.b.call(this,a,c);a.d("timeupdate",t.bind(this,this.da))}});
t.hb.prototype.e=function(){var a=t.b.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.C=t.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(this.C);return a};t.hb.prototype.da=function(){this.c.duration()&&(this.C.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+t.ua(this.c.duration()-this.c.currentTime()))};
t.Fa=t.q.extend({i:function(a,c){t.q.call(this,a,c)}});t.Fa.prototype.pa="Fullscreen";t.Fa.prototype.Q=function(){return"vjs-fullscreen-control "+t.q.prototype.Q.call(this)};t.Fa.prototype.p=function(){this.c.isFullScreen()?(this.c.cancelFullScreen(),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.c.requestFullScreen(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};t.gb=t.b.extend({i:function(a,c){t.b.call(this,a,c)}});t.gb.prototype.j={children:{seekBar:{}}};
t.gb.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};t.$b=t.O.extend({i:function(a,c){t.O.call(this,a,c);a.d("timeupdate",t.bind(this,this.Ba));a.I(t.bind(this,this.Ba))}});s=t.$b.prototype;s.j={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};s.uc="timeupdate";s.e=function(){return t.O.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};
s.Ba=function(){var a=this.c.Wa?this.c.u.currentTime:this.c.currentTime();this.a.setAttribute("aria-valuenow",t.round(100*this.xb(),2));this.a.setAttribute("aria-valuetext",t.ua(a,this.c.duration()))};s.xb=function(){return this.c.currentTime()/this.c.duration()};s.Sa=function(a){t.O.prototype.Sa.call(this,a);this.c.Wa=f;this.Jd=!this.c.paused();this.c.pause()};s.Gb=function(a){a=G(this,a)*this.c.duration();a==this.c.duration()&&(a-=0.1);this.c.currentTime(a)};
s.Hb=function(a){t.O.prototype.Hb.call(this,a);this.c.Wa=l;this.Jd&&this.c.play()};s.Ac=function(){this.c.currentTime(this.c.currentTime()+5)};s.zc=function(){this.c.currentTime(this.c.currentTime()-5)};t.eb=t.b.extend({i:function(a,c){t.b.call(this,a,c);a.d("progress",t.bind(this,this.update))}});t.eb.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};
t.eb.prototype.update=function(){this.a.style&&(this.a.style.width=t.round(100*this.c.bufferedPercent(),2)+"%")};t.Yb=t.b.extend({i:function(a,c){t.b.call(this,a,c)}});t.Yb.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};t.Ha=t.X.extend({i:function(a,c){t.X.call(this,a,c);a.d("timeupdate",t.bind(this,this.da))}});t.Ha.prototype.defaultValue="00:00";
t.Ha.prototype.e=function(){return t.X.prototype.e.call(this,"div",{className:"vjs-seek-handle","aria-live":"off"})};t.Ha.prototype.da=function(){var a=this.c.Wa?this.c.u.currentTime:this.c.currentTime();this.a.innerHTML='<span class="vjs-control-text">'+t.ua(a,this.c.duration())+"</span>"};t.jb=t.b.extend({i:function(a,c){t.b.call(this,a,c);a.f&&(a.f.n&&a.f.n.volumeControl===l)&&this.m("vjs-hidden");a.d("loadstart",t.bind(this,function(){a.f.n&&a.f.n.volumeControl===l?this.m("vjs-hidden"):this.r("vjs-hidden")}))}});
t.jb.prototype.j={children:{volumeBar:{}}};t.jb.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};t.ib=t.O.extend({i:function(a,c){t.O.call(this,a,c);a.d("volumechange",t.bind(this,this.Ba));a.I(t.bind(this,this.Ba))}});s=t.ib.prototype;s.Ba=function(){this.a.setAttribute("aria-valuenow",t.round(100*this.c.volume(),2));this.a.setAttribute("aria-valuetext",t.round(100*this.c.volume(),2)+"%")};
s.j={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};s.uc="volumechange";s.e=function(){return t.O.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};s.Gb=function(a){this.c.muted()&&this.c.muted(l);this.c.volume(G(this,a))};s.xb=function(){return this.c.muted()?0:this.c.volume()};s.Ac=function(){this.c.volume(this.c.volume()+0.1)};s.zc=function(){this.c.volume(this.c.volume()-0.1)};
t.ec=t.b.extend({i:function(a,c){t.b.call(this,a,c)}});t.ec.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};t.kb=t.X.extend();t.kb.prototype.defaultValue="00:00";t.kb.prototype.e=function(){return t.X.prototype.e.call(this,"div",{className:"vjs-volume-handle"})};
t.ea=t.q.extend({i:function(a,c){t.q.call(this,a,c);a.d("volumechange",t.bind(this,this.update));a.f&&(a.f.n&&a.f.n.volumeControl===l)&&this.m("vjs-hidden");a.d("loadstart",t.bind(this,function(){a.f.n&&a.f.n.volumeControl===l?this.m("vjs-hidden"):this.r("vjs-hidden")}))}});t.ea.prototype.e=function(){return t.q.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};
t.ea.prototype.p=function(){this.c.muted(this.c.muted()?l:f)};t.ea.prototype.update=function(){var a=this.c.volume(),c=3;0===a||this.c.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.c.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)t.r(this.a,"vjs-vol-"+a);t.m(this.a,"vjs-vol-"+c)};
t.na=t.S.extend({i:function(a,c){t.S.call(this,a,c);a.d("volumechange",t.bind(this,this.update));a.f&&(a.f.n&&a.f.n.Ec===l)&&this.m("vjs-hidden");a.d("loadstart",t.bind(this,function(){a.f.n&&a.f.n.Ec===l?this.m("vjs-hidden"):this.r("vjs-hidden")}));this.m("vjs-menu-button")}});t.na.prototype.Ma=function(){var a=new t.ma(this.c,{Vc:"div"}),c=new t.ib(this.c,t.l.A({Id:f},this.j.$d));a.V(c);return a};t.na.prototype.p=function(){t.ea.prototype.p.call(this);t.S.prototype.p.call(this)};
t.na.prototype.e=function(){return t.q.prototype.e.call(this,"div",{className:"vjs-volume-menu-button vjs-menu-button vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};t.na.prototype.update=t.ea.prototype.update;t.Ga=t.q.extend({i:function(a,c){t.q.call(this,a,c);a.poster()&&this.src(a.poster());(!a.poster()||!a.controls())&&this.D();a.d("posterchange",t.bind(this,function(){this.src(a.poster())}));a.d("play",t.bind(this,this.D))}});var S="backgroundSize"in t.G.style;
t.Ga.prototype.e=function(){var a=t.e("div",{className:"vjs-poster",tabIndex:-1});S||a.appendChild(t.e("img"));return a};t.Ga.prototype.src=function(a){var c=this.v();a!==b&&(S?c.style.backgroundImage='url("'+a+'")':c.firstChild.src=a)};t.Ga.prototype.p=function(){this.B().controls()&&this.c.play()};
t.Xb=t.b.extend({i:function(a,c){t.b.call(this,a,c);a.d("canplay",t.bind(this,this.D));a.d("canplaythrough",t.bind(this,this.D));a.d("playing",t.bind(this,this.D));a.d("seeking",t.bind(this,this.show));a.d("seeked",t.bind(this,this.D));a.d("error",t.bind(this,this.show));a.d("ended",t.bind(this,this.D));a.d("waiting",t.bind(this,this.show))}});t.Xb.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-loading-spinner"})};t.Za=t.q.extend();
t.Za.prototype.e=function(){return t.q.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:'<span aria-hidden="true"></span>',"aria-label":"play video"})};t.Za.prototype.p=function(){this.c.play()};
t.s=t.b.extend({i:function(a,c,d){c=c||{};c.xc=l;t.b.call(this,a,c,d);var e,g;g=this;e=this.B();a=function(){if(e.controls()&&!e.usingNativeControls()){var a;g.d("mousedown",g.p);g.d("touchstart",function(c){c.preventDefault();a=this.c.userActive()});g.d("touchmove",function(){a&&this.B().reportUserActivity()});F(g);g.d("tap",g.sd)}};c=t.bind(g,g.vd);this.I(a);e.d("controlsenabled",a);e.d("controlsdisabled",c)}});s=t.s.prototype;
s.vd=function(){this.o("tap");this.o("touchstart");this.o("touchmove");this.o("touchleave");this.o("touchcancel");this.o("touchend");this.o("click");this.o("mousedown")};s.p=function(a){0===a.button&&this.B().controls()&&(this.B().paused()?this.B().play():this.B().pause())};s.sd=function(){this.B().userActive(!this.B().userActive())};s.Mb=m();s.n={volumeControl:f,fullscreenResize:l,progressEvents:l,timeupdateEvents:l};t.media={};t.media.Ya="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function ea(){var a=t.media.Ya[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=t.media.Ya.length-1;0<=i;i--)t.s.prototype[t.media.Ya[i]]=ea();
t.h=t.s.extend({i:function(a,c,d){this.n.volumeControl=t.h.Uc();this.n.movingMediaElementInDOM=!t.Jc;this.n.fullscreenResize=f;t.s.call(this,a,c,d);for(d=t.h.cb.length-1;0<=d;d--)t.d(this.a,t.h.cb[d],t.bind(this.c,this.bd));(c=c.source)&&this.a.currentSrc===c.src&&0<this.a.networkState?a.k("loadstart"):c&&(this.a.src=c.src);if(t.bc&&a.options().nativeControlsForTouch!==l){var e,g,h,k;e=this;g=this.B();c=g.controls();e.a.controls=!!c;h=function(){e.a.controls=f};k=function(){e.a.controls=l};g.d("controlsenabled",
h);g.d("controlsdisabled",k);c=function(){g.o("controlsenabled",h);g.o("controlsdisabled",k)};e.d("dispose",c);g.d("usingcustomcontrols",c);g.usingNativeControls(f)}a.I(function(){this.M&&(this.j.autoplay&&this.paused())&&(delete this.M.poster,this.play())});this.Aa()}});s=t.h.prototype;s.dispose=function(){t.s.prototype.dispose.call(this)};
s.e=function(){var a=this.c,c=a.M,d;if(!c||this.n.movingMediaElementInDOM===l)c?(d=c.cloneNode(l),t.h.ic(c),c=d,a.M=j):c=t.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,t.yb(c,a.v());d=["autoplay","preload","loop","muted"];for(var e=d.length-1;0<=e;e--){var g=d[e];a.j[g]!==j&&(c[g]=a.j[g])}return c};s.bd=function(a){this.k(a);a.stopPropagation()};s.play=function(){this.a.play()};s.pause=function(){this.a.pause()};s.paused=function(){return this.a.paused};s.currentTime=function(){return this.a.currentTime};
s.xd=function(a){try{this.a.currentTime=a}catch(c){t.log(c,"Video is not ready. (Video.js)")}};s.duration=function(){return this.a.duration||0};s.buffered=function(){return this.a.buffered};s.volume=function(){return this.a.volume};s.Cd=function(a){this.a.volume=a};s.muted=function(){return this.a.muted};s.Ad=function(a){this.a.muted=a};s.width=function(){return this.a.offsetWidth};s.height=function(){return this.a.offsetHeight};
s.Xa=function(){return"function"==typeof this.a.webkitEnterFullScreen&&(/Android/.test(t.J)||!/Chrome|Mac OS X 10.5/.test(t.J))?f:l};s.jc=function(){var a=this.a;a.paused&&a.networkState<=a.Ld?(this.a.play(),setTimeout(function(){a.pause();a.webkitEnterFullScreen()},0)):a.webkitEnterFullScreen()};s.cd=function(){this.a.webkitExitFullScreen()};s.src=function(a){this.a.src=a};s.load=function(){this.a.load()};s.currentSrc=function(){return this.a.currentSrc};s.poster=function(){return this.a.poster};
s.Mb=function(a){this.a.poster=a};s.Ta=function(){return this.a.Ta};s.Bd=function(a){this.a.Ta=a};s.autoplay=function(){return this.a.autoplay};s.wd=function(a){this.a.autoplay=a};s.controls=function(){return this.a.controls};s.loop=function(){return this.a.loop};s.zd=function(a){this.a.loop=a};s.error=function(){return this.a.error};s.seeking=function(){return this.a.seeking};s.ended=function(){return this.a.ended};t.h.isSupported=function(){try{t.G.volume=0.5}catch(a){return l}return!!t.G.canPlayType};
t.h.ob=function(a){try{return!!t.G.canPlayType(a.type)}catch(c){return""}};t.h.Uc=function(){var a=t.G.volume;t.G.volume=a/2+0.1;return a!==t.G.volume};var T,fa=/^application\/(?:x-|vnd\.apple\.)mpegurl/i,ga=/^video\/mp4/i;
t.h.tc=function(){4<=t.Rb&&(T||(T=t.G.constructor.prototype.canPlayType),t.G.constructor.prototype.canPlayType=function(a){return a&&fa.test(a)?"maybe":T.call(this,a)});t.Nc&&(T||(T=t.G.constructor.prototype.canPlayType),t.G.constructor.prototype.canPlayType=function(a){return a&&ga.test(a)?"maybe":T.call(this,a)})};t.h.Hd=function(){var a=t.G.constructor.prototype.canPlayType;t.G.constructor.prototype.canPlayType=T;T=j;return a};t.h.tc();t.h.cb="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
t.h.ic=function(a){if(a){a.player=j;for(a.parentNode&&a.parentNode.removeChild(a);a.hasChildNodes();)a.removeChild(a.firstChild);a.removeAttribute("src");if("function"===typeof a.load)try{a.load()}catch(c){}}};
t.g=t.s.extend({i:function(a,c,d){t.s.call(this,a,c,d);var e=c.source;d=c.parentEl;var g=this.a=t.e("div",{id:a.id()+"_temp_flash"}),h=a.id()+"_flash_api";a=a.j;var k=t.l.A({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.Ta,loop:a.loop,muted:a.muted},c.flashVars),q=t.l.A({wmode:"opaque",bgcolor:"#000000"},c.params),n=t.l.A({id:h,name:h,"class":"vjs-tech"},c.attributes),u;e&&(e.type&&t.g.kd(e.type)?
(a=t.g.Bc(e.src),k.rtmpConnection=encodeURIComponent(a.rb),k.rtmpStream=encodeURIComponent(a.Nb)):k.src=encodeURIComponent(t.mc(e.src)));this.setCurrentTime=function(a){u=a;this.a.vjs_setProperty("currentTime",a)};this.currentTime=function(){return this.seeking()?u:this.a.vjs_getProperty("currentTime")};t.yb(g,d);c.startTime&&this.I(function(){this.load();this.play();this.currentTime(c.startTime)});t.Vb&&this.I(function(){t.d(this.v(),"mousemove",t.bind(this,function(){this.B().k({type:"mousemove",
bubbles:l})}))});if(c.iFrameMode===f&&!t.Vb){var D=t.e("iframe",{id:h+"_iframe",name:h+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";t.d(D,"load",t.bind(this,function(){var a,d=D.contentWindow;a=D.contentDocument?D.contentDocument:D.contentWindow.document;a.write(t.g.nc(c.swf,k,q,n));d.player=this.c;d.ready=t.bind(this.c,function(c){var d=this.f;d.a=a.getElementById(c);
t.g.qb(d)});d.events=t.bind(this.c,function(a,c){this&&"flash"===this.ya&&this.k(c)});d.errors=t.bind(this.c,function(a,c){t.log("Flash Error",c)})}));g.parentNode.replaceChild(D,g)}else t.g.ad(c.swf,g,k,q,n)}});s=t.g.prototype;s.dispose=function(){t.s.prototype.dispose.call(this)};s.play=function(){this.a.vjs_play()};s.pause=function(){this.a.vjs_pause()};
s.src=function(a){if(a===b)return this.currentSrc();t.g.jd(a)?(a=t.g.Bc(a),this.Vd(a.rb),this.Wd(a.Nb)):(a=t.mc(a),this.a.vjs_src(a));if(this.c.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};s.currentSrc=function(){var a=this.a.vjs_getProperty("currentSrc");if(a==j){var c=this.rtmpConnection(),d=this.rtmpStream();c&&d&&(a=t.g.Dd(c,d))}return a};s.load=function(){this.a.vjs_load()};s.poster=function(){this.a.vjs_getProperty("poster")};s.Mb=m();s.buffered=function(){return t.tb(0,this.a.vjs_getProperty("buffered"))};
s.Xa=r(l);s.jc=r(l);var U=t.g.prototype,V="rtmpConnection rtmpStream preload defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),W="error networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function ha(){var a=V[X],c=a.charAt(0).toUpperCase()+a.slice(1);U["set"+c]=function(c){return this.a.vjs_setProperty(a,c)}}
function Y(a){U[a]=function(){return this.a.vjs_getProperty(a)}}var X;for(X=0;X<V.length;X++)Y(V[X]),ha();for(X=0;X<W.length;X++)Y(W[X]);t.g.isSupported=function(){return 10<=t.g.version()[0]};t.g.ob=function(a){if(!a.type)return"";a=a.type.replace(/;.*/,"").toLowerCase();if(a in t.g.ed||a in t.g.Cc)return"maybe"};t.g.ed={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};t.g.Cc={"rtmp/mp4":"MP4","rtmp/flv":"FLV"};
t.g.onReady=function(a){a=t.v(a);var c=a.player||a.parentNode.player,d=c.f;a.player=c;d.a=a;t.g.qb(d)};t.g.qb=function(a){a.v().vjs_getProperty?a.Aa():setTimeout(function(){t.g.qb(a)},50)};t.g.onEvent=function(a,c){t.v(a).player.k(c)};t.g.onError=function(a,c){t.v(a).player.k("error");t.log("Flash Error",c,a)};
t.g.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
t.g.ad=function(a,c,d,e,g){a=t.g.nc(a,d,e,g);a=t.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var h=d.childNodes[0];setTimeout(function(){h.style.display="block"},1E3)};
t.g.nc=function(a,c,d,e){var g="",h="",k="";c&&t.l.sa(c,function(a,c){g+=a+"="+c+"&amp;"});d=t.l.A({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);t.l.sa(d,function(a,c){h+='<param name="'+a+'" value="'+c+'" />'});e=t.l.A({data:a,width:"100%",height:"100%"},e);t.l.sa(e,function(a,c){k+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+h+"</object>"};t.g.Dd=function(a,c){return a+"&"+c};
t.g.Bc=function(a){var c={rb:"",Nb:""};if(!a)return c;var d=a.indexOf("&"),e;-1!==d?e=d+1:(d=e=a.lastIndexOf("/")+1,0===d&&(d=e=a.length));c.rb=a.substring(0,d);c.Nb=a.substring(e,a.length);return c};t.g.kd=function(a){return a in t.g.Cc};t.g.Pc=/^rtmp[set]?:\/\//i;t.g.jd=function(a){return t.g.Pc.test(a)};
t.Oc=t.b.extend({i:function(a,c,d){t.b.call(this,a,c,d);if(!a.j.sources||0===a.j.sources.length){c=0;for(d=a.j.techOrder;c<d.length;c++){var e=t.Z(d[c]),g=window.videojs[e];if(g&&g.isSupported()){J(a,e);break}}}else a.src(a.j.sources)}});t.Player.prototype.textTracks=function(){return this.za=this.za||[]};
function ia(a,c,d,e,g){var h=a.za=a.za||[];g=g||{};g.kind=c;g.label=d;g.language=e;c=t.Z(c||"subtitles");var k=new window.videojs[c+"Track"](a,g);h.push(k);k.Na()&&a.I(function(){setTimeout(function(){k.show()},0)})}function ja(a,c,d){for(var e=a.za,g=0,h=e.length,k,q;g<h;g++)k=e[g],k.id()===c?(k.show(),q=k):d&&(k.H()==d&&0<k.mode())&&k.disable();(c=q?q.H():d?d:l)&&a.k(c+"trackchange")}
t.w=t.b.extend({i:function(a,c){t.b.call(this,a,c);this.R=c.id||"vjs_"+c.kind+"_"+c.language+"_"+t.t++;this.yc=c.src;this.Yc=c["default"]||c.dflt;this.Fd=c.title;this.Sd=c.srclang;this.ld=c.label;this.$=[];this.lb=[];this.ha=this.ia=0;this.c.d("fullscreenchange",t.bind(this,this.Rc))}});s=t.w.prototype;s.H=p("F");s.src=p("yc");s.Na=p("Yc");s.title=p("Fd");s.label=p("ld");s.Wc=p("$");s.Qc=p("lb");s.readyState=p("ia");s.mode=p("ha");
s.Rc=function(){this.a.style.fontSize=this.c.isFullScreen()?140*(screen.width/this.c.width())+"%":""};s.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-"+this.F+" vjs-text-track"})};s.show=function(){ka(this);this.ha=2;t.b.prototype.show.call(this)};s.D=function(){ka(this);this.ha=1;t.b.prototype.D.call(this)};
s.disable=function(){2==this.ha&&this.D();this.c.o("timeupdate",t.bind(this,this.update,this.R));this.c.o("ended",t.bind(this,this.reset,this.R));this.reset();this.c.ga("textTrackDisplay").removeChild(this);this.ha=0};function ka(a){0===a.ia&&a.load();0===a.ha&&(a.c.d("timeupdate",t.bind(a,a.update,a.R)),a.c.d("ended",t.bind(a,a.reset,a.R)),("captions"===a.F||"subtitles"===a.F)&&a.c.ga("textTrackDisplay").V(a))}
s.load=function(){0===this.ia&&(this.ia=1,t.get(this.yc,t.bind(this,this.td),t.bind(this,this.Fb)))};s.Fb=function(a){this.error=a;this.ia=3;this.k("error")};s.td=function(a){var c,d;a=a.split("\n");for(var e="",g=1,h=a.length;g<h;g++)if(e=t.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=t.trim(a[++g])):c=this.$.length;c={id:c,index:this.$.length};d=e.split(" --\x3e ");c.startTime=la(d[0]);c.ta=la(d[1]);for(d=[];a[++g]&&(e=t.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.$.push(c)}this.ia=2;this.k("loaded")};
function la(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
s.update=function(){if(0<this.$.length){var a=this.c.currentTime();if(this.Kb===b||a<this.Kb||this.Pa<=a){var c=this.$,d=this.c.duration(),e=0,g=l,h=[],k,q,n,u;a>=this.Pa||this.Pa===b?u=this.vb!==b?this.vb:0:(g=f,u=this.Bb!==b?this.Bb:c.length-1);for(;;){n=c[u];if(n.ta<=a)e=Math.max(e,n.ta),n.Ja&&(n.Ja=l);else if(a<n.startTime){if(d=Math.min(d,n.startTime),n.Ja&&(n.Ja=l),!g)break}else g?(h.splice(0,0,n),q===b&&(q=u),k=u):(h.push(n),k===b&&(k=u),q=u),d=Math.min(d,n.ta),e=Math.max(e,n.startTime),n.Ja=
f;if(g)if(0===u)break;else u--;else if(u===c.length-1)break;else u++}this.lb=h;this.Pa=d;this.Kb=e;this.vb=k;this.Bb=q;a=this.lb;c="";d=0;for(e=a.length;d<e;d++)c+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=c;this.k("cuechange")}}};s.reset=function(){this.Pa=0;this.Kb=this.c.duration();this.Bb=this.vb=0};t.Tb=t.w.extend();t.Tb.prototype.F="captions";t.ac=t.w.extend();t.ac.prototype.F="subtitles";t.Ub=t.w.extend();t.Ub.prototype.F="chapters";
t.cc=t.b.extend({i:function(a,c,d){t.b.call(this,a,c,d);if(a.j.tracks&&0<a.j.tracks.length){c=this.c;a=a.j.tracks;for(var e=0;e<a.length;e++)d=a[e],ia(c,d.kind,d.label,d.language,d)}}});t.cc.prototype.e=function(){return t.b.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};t.Y=t.N.extend({i:function(a,c){var d=this.ca=c.track;c.label=d.label();c.selected=d.Na();t.N.call(this,a,c);this.c.d(d.H()+"trackchange",t.bind(this,this.update))}});
t.Y.prototype.p=function(){t.N.prototype.p.call(this);ja(this.c,this.ca.R,this.ca.H())};t.Y.prototype.update=function(){this.selected(2==this.ca.mode())};t.fb=t.Y.extend({i:function(a,c){c.track={H:function(){return c.kind},B:a,label:function(){return c.kind+" off"},Na:r(l),mode:r(l)};t.Y.call(this,a,c);this.selected(f)}});t.fb.prototype.p=function(){t.Y.prototype.p.call(this);ja(this.c,this.ca.R,this.ca.H())};
t.fb.prototype.update=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.H()==this.ca.H()&&2==e.mode()&&(g=l);this.selected(g)};t.T=t.S.extend({i:function(a,c){t.S.call(this,a,c);1>=this.L.length&&this.D()}});t.T.prototype.ra=function(){var a=[],c;a.push(new t.fb(this.c,{kind:this.F}));for(var d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.H()===this.F&&a.push(new t.Y(this.c,{track:c}));return a};
t.Ca=t.T.extend({i:function(a,c,d){t.T.call(this,a,c,d);this.a.setAttribute("aria-label","Captions Menu")}});t.Ca.prototype.F="captions";t.Ca.prototype.pa="Captions";t.Ca.prototype.className="vjs-captions-button";t.Ia=t.T.extend({i:function(a,c,d){t.T.call(this,a,c,d);this.a.setAttribute("aria-label","Subtitles Menu")}});t.Ia.prototype.F="subtitles";t.Ia.prototype.pa="Subtitles";t.Ia.prototype.className="vjs-subtitles-button";
t.Da=t.T.extend({i:function(a,c,d){t.T.call(this,a,c,d);this.a.setAttribute("aria-label","Chapters Menu")}});s=t.Da.prototype;s.F="chapters";s.pa="Chapters";s.className="vjs-chapters-button";s.ra=function(){for(var a=[],c,d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.H()===this.F&&a.push(new t.Y(this.c,{track:c}));return a};
s.Ma=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g,h=this.L=[];c<d;c++)if(e=a[c],e.H()==this.F&&e.Na()){if(2>e.readyState()){this.Pd=e;e.d("loaded",t.bind(this,this.Ma));return}g=e;break}a=this.va=new t.ma(this.c);a.fa().appendChild(t.e("li",{className:"vjs-menu-title",innerHTML:t.Z(this.F),Ed:-1}));if(g){e=g.$;for(var k,c=0,d=e.length;c<d;c++)k=e[c],k=new t.$a(this.c,{track:g,cue:k}),h.push(k),a.V(k)}0<this.L.length&&this.show();return a};
t.$a=t.N.extend({i:function(a,c){var d=this.ca=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.ta;t.N.call(this,a,c);d.d("cuechange",t.bind(this,this.update))}});t.$a.prototype.p=function(){t.N.prototype.p.call(this);this.c.currentTime(this.cue.startTime);this.update(this.cue.startTime)};t.$a.prototype.update=function(){var a=this.cue,c=this.c.currentTime();this.selected(a.startTime<=c&&c<a.ta)};
t.l.A(t.Ea.prototype.j.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)t.JSON=window.JSON;else{t.JSON={};var Z=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;t.JSON.parse=function(a,c){function d(a,e){var k,q,n=a[e];if(n&&"object"===typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(q=d(n,k),q!==b?n[k]=q:delete n[k]);return c.call(a,e,n)}var e;a=String(a);Z.lastIndex=0;Z.test(a)&&(a=a.replace(Z,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
t.fc=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==j&&(a=t.JSON.parse(a||"{}"),videojs(c,a)));else{t.mb();break}else t.Fc||t.mb()};t.mb=function(){setTimeout(t.fc,1)};"complete"===document.readyState?t.Fc=f:t.U(window,"load",function(){t.Fc=f});t.mb();t.ud=function(a,c){t.Player.prototype[a]=c};var ma=this;ma.Kd=f;function $(a,c){var d=a.split("."),e=ma;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",t);$("_V_",t);$("videojs.options",t.options);$("videojs.players",t.wa);$("videojs.TOUCH_ENABLED",t.bc);$("videojs.cache",t.qa);$("videojs.Component",t.b);t.b.prototype.player=t.b.prototype.B;t.b.prototype.options=t.b.prototype.options;t.b.prototype.init=t.b.prototype.i;t.b.prototype.dispose=t.b.prototype.dispose;t.b.prototype.createEl=t.b.prototype.e;t.b.prototype.contentEl=t.b.prototype.fa;t.b.prototype.el=t.b.prototype.v;t.b.prototype.addChild=t.b.prototype.V;
t.b.prototype.getChild=t.b.prototype.ga;t.b.prototype.getChildById=t.b.prototype.fd;t.b.prototype.children=t.b.prototype.children;t.b.prototype.initChildren=t.b.prototype.pc;t.b.prototype.removeChild=t.b.prototype.removeChild;t.b.prototype.on=t.b.prototype.d;t.b.prototype.off=t.b.prototype.o;t.b.prototype.one=t.b.prototype.U;t.b.prototype.trigger=t.b.prototype.k;t.b.prototype.triggerReady=t.b.prototype.Aa;t.b.prototype.show=t.b.prototype.show;t.b.prototype.hide=t.b.prototype.D;
t.b.prototype.width=t.b.prototype.width;t.b.prototype.height=t.b.prototype.height;t.b.prototype.dimensions=t.b.prototype.Zc;t.b.prototype.ready=t.b.prototype.I;t.b.prototype.addClass=t.b.prototype.m;t.b.prototype.removeClass=t.b.prototype.r;t.b.prototype.buildCSSClass=t.b.prototype.Q;t.Player.prototype.ended=t.Player.prototype.ended;$("videojs.MediaLoader",t.Oc);$("videojs.TextTrackDisplay",t.cc);$("videojs.ControlBar",t.Ea);$("videojs.Button",t.q);$("videojs.PlayToggle",t.Zb);
$("videojs.FullscreenToggle",t.Fa);$("videojs.BigPlayButton",t.Za);$("videojs.LoadingSpinner",t.Xb);$("videojs.CurrentTimeDisplay",t.ab);$("videojs.DurationDisplay",t.bb);$("videojs.TimeDivider",t.dc);$("videojs.RemainingTimeDisplay",t.hb);$("videojs.LiveDisplay",t.Wb);$("videojs.Slider",t.O);$("videojs.ProgressControl",t.gb);$("videojs.SeekBar",t.$b);$("videojs.LoadProgressBar",t.eb);$("videojs.PlayProgressBar",t.Yb);$("videojs.SeekHandle",t.Ha);$("videojs.VolumeControl",t.jb);
$("videojs.VolumeBar",t.ib);$("videojs.VolumeLevel",t.ec);$("videojs.VolumeMenuButton",t.na);$("videojs.VolumeHandle",t.kb);$("videojs.MuteToggle",t.ea);$("videojs.PosterImage",t.Ga);$("videojs.Menu",t.ma);$("videojs.MenuItem",t.N);$("videojs.MenuButton",t.S);t.S.prototype.createItems=t.S.prototype.ra;t.T.prototype.createItems=t.T.prototype.ra;t.Da.prototype.createItems=t.Da.prototype.ra;$("videojs.SubtitlesButton",t.Ia);$("videojs.CaptionsButton",t.Ca);$("videojs.ChaptersButton",t.Da);
$("videojs.MediaTechController",t.s);t.s.prototype.features=t.s.prototype.n;t.s.prototype.n.volumeControl=t.s.prototype.n.Ec;t.s.prototype.n.fullscreenResize=t.s.prototype.n.Qd;t.s.prototype.n.progressEvents=t.s.prototype.n.Ud;t.s.prototype.n.timeupdateEvents=t.s.prototype.n.Xd;t.s.prototype.setPoster=t.s.prototype.Mb;$("videojs.Html5",t.h);t.h.Events=t.h.cb;t.h.isSupported=t.h.isSupported;t.h.canPlaySource=t.h.ob;t.h.patchCanPlayType=t.h.tc;t.h.unpatchCanPlayType=t.h.Hd;
t.h.prototype.setCurrentTime=t.h.prototype.xd;t.h.prototype.setVolume=t.h.prototype.Cd;t.h.prototype.setMuted=t.h.prototype.Ad;t.h.prototype.setPreload=t.h.prototype.Bd;t.h.prototype.setAutoplay=t.h.prototype.wd;t.h.prototype.setLoop=t.h.prototype.zd;t.h.prototype.enterFullScreen=t.h.prototype.jc;t.h.prototype.exitFullScreen=t.h.prototype.cd;$("videojs.Flash",t.g);t.g.isSupported=t.g.isSupported;t.g.canPlaySource=t.g.ob;t.g.onReady=t.g.onReady;$("videojs.TextTrack",t.w);t.w.prototype.label=t.w.prototype.label;
t.w.prototype.kind=t.w.prototype.H;t.w.prototype.mode=t.w.prototype.mode;t.w.prototype.cues=t.w.prototype.Wc;t.w.prototype.activeCues=t.w.prototype.Qc;$("videojs.CaptionsTrack",t.Tb);$("videojs.SubtitlesTrack",t.ac);$("videojs.ChaptersTrack",t.Ub);$("videojs.autoSetup",t.fc);$("videojs.plugin",t.ud);$("videojs.createTimeRange",t.tb);$("videojs.util",t.ka);t.ka.mergeOptions=t.ka.Eb;})();
